# FRUIT IMAGE RECOGNITION PROJECT(non-linear SVM)

In [40]:
#changing image to pixel format
import cv2
img=cv2.imread(r"C:\Users\Admin\PYTHON\Machine_Learning\Support vector Machine algorithm\FRUIT_IMAGES\BANANA\Image_2.jpg")
pixel=img.flatten()/255.0
'''
img.flatten(): This flattens the 2D or 3D array of pixel values in the image to a 1D array. The flatten() method in NumPy converts a multi-dimensional array into a one-dimensional array.
/ 255.0: This normalizes the pixel values by dividing each value by 255.0. This is a common technique to scale the pixel values between 0 and 1. In many image processing tasks, pixel values are represented in the range [0, 255], and normalizing helps bring them to a more standard range.
'''

'\nimg.flatten(): This flattens the 2D or 3D array of pixel values in the image to a 1D array. The flatten() method in NumPy converts a multi-dimensional array into a one-dimensional array.\n/ 255.0: This normalizes the pixel values by dividing each value by 255.0. This is a common technique to scale the pixel values between 0 and 1. In many image processing tasks, pixel values are represented in the range [0, 255], and normalizing helps bring them to a more standard range.\n'

In [41]:
len(pixel)#it's changed the image pixel from 0 to 1 range

518400

In [3]:
pixel

array([0.0627451, 0.0627451, 0.0627451, ..., 0.0627451, 0.0627451,
       0.0627451])

In [4]:
#we going to change all the images to 0-1 range pixel value and create as a dataset
#create a dataset with column 0 to 518399
import pandas as pd
li=[item for item in range(0,518400)]
dd=pd.DataFrame(columns=li)
dd
    

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
Index: []

[0 rows x 518400 columns]

In [5]:
#getting pixel values from 40 imagesand store to dataset
ruits=['APPLE','BANANA','MANGO','GRAPHES']
labels=[]
column_names=dd.columns
for i in fruits:
    for j in range(1,11):
        img=cv2.imread(r"C:\Users\Admin\PYTHON\Machine_Learning\Support vector Machine algorithm\FRUIT_IMAGES\{}\Image_{}.jpg".format(i,j))
        pixel=img.flatten()/255.0
        label=i
        index=len(dd)
        dic={}
        for ii,jj in zip(pixel,column_names):
            dic.update({jj:ii})
        dd.loc[index]=dic
        labels.append(label)

In [6]:
dd

0         1         2         3         4         5         6       \
0   0.988235  0.988235  0.988235  0.996078  0.996078  0.996078  0.988235   
1   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.949020  0.949020  0.949020  0.949020  0.949020  0.949020  0.949020   
3   0.843137  0.619608  0.415686  0.796078  0.572549  0.368627  0.749020   
4   1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
5   0.043137  0.015686  0.043137  0.054902  0.027451  0.054902  0.066667   
6   0.141176  0.333333  0.639216  0.117647  0.341176  0.635294  0.137255   
7   0.596078  0.623529  0.517647  0.564706  0.592157  0.486275  0.564706   
8   0.196078  0.192157  0.227451  0.196078  0.192157  0.227451  0.196078   
9   1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
10  0.996078  0.992157  1.000000  0.996078  0.992157  1.000000  0.996078   
11  0.062745  0.062745  0.062745  0.062745  0.062745  0.062745  0.062745   
12  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
13  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
14  0.027451  0.027451  0.027451  0.082353  0.082353  0.082353  0.054902   
15  0.000000  0.949020  0.996078  0.000000  0.949020  0.996078  0.000000   
16  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157   
17  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
18  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
19  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157   
20  0.027451  0.407843  0.184314  0.019608  0.400000  0.176471  0.019608   
21  0.419608  0.325490  0.254902  0.419608  0.325490  0.254902  0.415686   
22  0.650980  0.784314  0.901961  0.647059  0.780392  0.898039  0.654902   
23  0.007843  0.090196  0.266667  0.007843  0.090196  0.266667  0.003922   
24  0.647059  0.658824  0.678431  0.654902  0.666667  0.686275  0.650980   
25  0.172549  0.172549  0.172549  0.172549  0.172549  0.172549  0.172549   
26  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
27  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
28  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
29  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
30  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
31  0.203922  0.635294  0.525490  0.223529  0.654902  0.545098  0.239216   
32  0.239216  0.705882  0.623529  0.243137  0.709804  0.627451  0.243137   
33  0.325490  0.682353  0.647059  0.325490  0.682353  0.647059  0.321569   
34  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
35  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
36  0.133333  0.294118  0.184314  0.149020  0.309804  0.200000  0.152941   
37  0.301961  0.627451  0.411765  0.223529  0.600000  0.388235  0.192157   
38  0.352941  0.913725  0.941176  0.356863  0.913725  0.941176  0.356863   
39  0.168627  0.325490  0.345098  0.168627  0.325490  0.345098  0.168627   

      7         8         9       ...    518390    518391    518392    518393  \
0   0.988235  0.988235  0.988235  ...       NaN       NaN       NaN       NaN   
1   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
2   0.949020  0.949020  0.949020  ...  0.964706  0.964706  0.964706  0.964706   
3   0.525490  0.321569  0.749020  ...  0.250980  0.780392  0.552941  0.270588   
4   1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000   
5   0.039216  0.066667  0.062745  ...  0.070588  0.078431  0.070588  0.066667   
6   0.337255  0.650980  0.117647  ...  0.133333  0.023529  0.078431  0.125490   
7   0.576471  0.474510  0.580392  ...  0.101961  0.137255  0.247059  0.105882   
8   0.192157  0.227451  0.196078  ...  0.396078  0.200000  0.250980  0.400000   
9   1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000  

In [7]:
#filling 0 to where ever null value is present
dd.fillna(0,inplace=True)

In [8]:
dd

0         1         2         3         4         5         6       \
0   0.988235  0.988235  0.988235  0.996078  0.996078  0.996078  0.988235   
1   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.949020  0.949020  0.949020  0.949020  0.949020  0.949020  0.949020   
3   0.843137  0.619608  0.415686  0.796078  0.572549  0.368627  0.749020   
4   1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
5   0.043137  0.015686  0.043137  0.054902  0.027451  0.054902  0.066667   
6   0.141176  0.333333  0.639216  0.117647  0.341176  0.635294  0.137255   
7   0.596078  0.623529  0.517647  0.564706  0.592157  0.486275  0.564706   
8   0.196078  0.192157  0.227451  0.196078  0.192157  0.227451  0.196078   
9   1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
10  0.996078  0.992157  1.000000  0.996078  0.992157  1.000000  0.996078   
11  0.062745  0.062745  0.062745  0.062745  0.062745  0.062745  0.062745   
12  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
13  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
14  0.027451  0.027451  0.027451  0.082353  0.082353  0.082353  0.054902   
15  0.000000  0.949020  0.996078  0.000000  0.949020  0.996078  0.000000   
16  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157   
17  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
18  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
19  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157   
20  0.027451  0.407843  0.184314  0.019608  0.400000  0.176471  0.019608   
21  0.419608  0.325490  0.254902  0.419608  0.325490  0.254902  0.415686   
22  0.650980  0.784314  0.901961  0.647059  0.780392  0.898039  0.654902   
23  0.007843  0.090196  0.266667  0.007843  0.090196  0.266667  0.003922   
24  0.647059  0.658824  0.678431  0.654902  0.666667  0.686275  0.650980   
25  0.172549  0.172549  0.172549  0.172549  0.172549  0.172549  0.172549   
26  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
27  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
28  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
29  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
30  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
31  0.203922  0.635294  0.525490  0.223529  0.654902  0.545098  0.239216   
32  0.239216  0.705882  0.623529  0.243137  0.709804  0.627451  0.243137   
33  0.325490  0.682353  0.647059  0.325490  0.682353  0.647059  0.321569   
34  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
35  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
36  0.133333  0.294118  0.184314  0.149020  0.309804  0.200000  0.152941   
37  0.301961  0.627451  0.411765  0.223529  0.600000  0.388235  0.192157   
38  0.352941  0.913725  0.941176  0.356863  0.913725  0.941176  0.356863   
39  0.168627  0.325490  0.345098  0.168627  0.325490  0.345098  0.168627   

      7         8         9       ...    518390    518391    518392    518393  \
0   0.988235  0.988235  0.988235  ...  0.000000  0.000000  0.000000  0.000000   
1   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
2   0.949020  0.949020  0.949020  ...  0.964706  0.964706  0.964706  0.964706   
3   0.525490  0.321569  0.749020  ...  0.250980  0.780392  0.552941  0.270588   
4   1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000   
5   0.039216  0.066667  0.062745  ...  0.070588  0.078431  0.070588  0.066667   
6   0.337255  0.650980  0.117647  ...  0.133333  0.023529  0.078431  0.125490   
7   0.576471  0.474510  0.580392  ...  0.101961  0.137255  0.247059  0.105882   
8   0.192157  0.227451  0.196078  ...  0.396078  0.200000  0.250980  0.400000   
9   1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000  

In [9]:
#adding label new column to dataset
dd['Labels']=labels

In [10]:
dd

0         1         2         3         4         5         6  \
0   0.988235  0.988235  0.988235  0.996078  0.996078  0.996078  0.988235   
1   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.949020  0.949020  0.949020  0.949020  0.949020  0.949020  0.949020   
3   0.843137  0.619608  0.415686  0.796078  0.572549  0.368627  0.749020   
4   1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
5   0.043137  0.015686  0.043137  0.054902  0.027451  0.054902  0.066667   
6   0.141176  0.333333  0.639216  0.117647  0.341176  0.635294  0.137255   
7   0.596078  0.623529  0.517647  0.564706  0.592157  0.486275  0.564706   
8   0.196078  0.192157  0.227451  0.196078  0.192157  0.227451  0.196078   
9   1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
10  0.996078  0.992157  1.000000  0.996078  0.992157  1.000000  0.996078   
11  0.062745  0.062745  0.062745  0.062745  0.062745  0.062745  0.062745   
12  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
13  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
14  0.027451  0.027451  0.027451  0.082353  0.082353  0.082353  0.054902   
15  0.000000  0.949020  0.996078  0.000000  0.949020  0.996078  0.000000   
16  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157   
17  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
18  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
19  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157   
20  0.027451  0.407843  0.184314  0.019608  0.400000  0.176471  0.019608   
21  0.419608  0.325490  0.254902  0.419608  0.325490  0.254902  0.415686   
22  0.650980  0.784314  0.901961  0.647059  0.780392  0.898039  0.654902   
23  0.007843  0.090196  0.266667  0.007843  0.090196  0.266667  0.003922   
24  0.647059  0.658824  0.678431  0.654902  0.666667  0.686275  0.650980   
25  0.172549  0.172549  0.172549  0.172549  0.172549  0.172549  0.172549   
26  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
27  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
28  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
29  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
30  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
31  0.203922  0.635294  0.525490  0.223529  0.654902  0.545098  0.239216   
32  0.239216  0.705882  0.623529  0.243137  0.709804  0.627451  0.243137   
33  0.325490  0.682353  0.647059  0.325490  0.682353  0.647059  0.321569   
34  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
35  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
36  0.133333  0.294118  0.184314  0.149020  0.309804  0.200000  0.152941   
37  0.301961  0.627451  0.411765  0.223529  0.600000  0.388235  0.192157   
38  0.352941  0.913725  0.941176  0.356863  0.913725  0.941176  0.356863   
39  0.168627  0.325490  0.345098  0.168627  0.325490  0.345098  0.168627   

           7         8         9  ...    518391    518392    518393    518394  \
0   0.988235  0.988235  0.988235  ...  0.000000  0.000000  0.000000  0.000000   
1   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
2   0.949020  0.949020  0.949020  ...  0.964706  0.964706  0.964706  0.964706   
3   0.525490  0.321569  0.749020  ...  0.780392  0.552941  0.270588  0.788235   
4   1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000   
5   0.039216  0.066667  0.062745  ...  0.078431  0.070588  0.066667  0.078431   
6   0.337255  0.650980  0.117647  ...  0.023529  0.078431  0.125490  0.011765   
7   0.576471  0.474510  0.580392  ...  0.137255  0.247059  0.105882  0.133333   
8   0.192157  0.227451  0.196078  ...  0.200000  0.250980  0.400000  0.200000   
9   1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000   
10 

In [76]:
#applying standared scaler for pixel values 
from sklearn.preprocessing import StandardScaler
lab=StandardScaler()
x=lab.fit_transform(dd.iloc[:,:518400])

In [88]:
#change the label column into numeric label column
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
y=l.fit_transform(dd['Labels'])

In [89]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [90]:
x

array([[ 1.02985257,  0.89334308,  0.90260303, ..., -1.14048027,
        -1.43722029, -1.36151093],
       [-1.35766213, -1.78828237, -1.73227636, ..., -1.14048027,
        -1.43722029, -1.36151093],
       [ 0.93510993,  0.78692937,  0.79804432, ...,  1.18009993,
         0.99522684,  1.01599884],
       ...,
       [-0.62814375, -0.08566304, -0.63440995, ..., -1.14048027,
        -1.43722029, -1.36151093],
       [-0.50497831,  0.69115704,  0.77713258, ..., -0.95181521,
        -1.27901234, -1.02324735],
       [-0.95026875, -0.90504859, -0.81215975, ..., -0.04622294,
         0.75791493,  0.21383091]])

In [91]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [92]:
#seggregate the value to train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [93]:
x_train

array([[ 1.05827537,  0.92526719,  0.93397064, ...,  1.26499921,
         1.06444282,  1.08365156],
       [ 1.05827537,  0.92526719,  0.93397064, ...,  1.26499921,
         1.08421881,  1.10298091],
       [-0.62814375, -0.08566304, -0.63440995, ..., -1.14048027,
        -1.43722029, -1.36151093],
       ...,
       [-0.50497831,  0.69115704,  0.77713258, ..., -0.95181521,
        -1.27901234, -1.02324735],
       [ 0.67930478, -0.10694578, -0.62395408, ...,  0.71787054,
        -0.06278878, -0.71397778],
       [ 1.02985257,  0.89334308,  0.90260303, ..., -1.14048027,
        -1.43722029, -1.36151093]])

In [168]:
#applying the SVM algorithm
from sklearn import svm
sv=svm.SVC(kernel="rbf")#rbf-Radial Basis Function.
sv.fit(x_train,y_train)

SVC()

In [169]:
#predicting the values by x_test values
y_prd=sv.predict(x_test)

In [170]:
x_test

array([[ 0.21506581,  0.3399918 ,  0.67257388, ...,  0.41600645,
         0.07564317,  0.09785482],
       [-1.29134228, -0.6815798 , -1.24085045, ..., -0.74428365,
        -0.13200475, -0.71397778],
       [-0.94079449, -1.32006205, -1.27221806, ...,  0.28394091,
         0.12508316,  0.19450156],
       ...,
       [-1.2060739 , -1.61802044, -1.56498243, ..., -0.98954823,
        -1.27901234, -1.20687615],
       [-1.35766213, -1.78828237, -1.73227636, ..., -1.14048027,
        -1.43722029, -1.36151093],
       [ 1.05827537,  0.92526719,  0.93397064, ..., -0.65938438,
         0.86668289,  1.10298091]])

In [171]:
#predicted values by algorithm
y_prd

array([2, 2, 2, 2, 2, 2, 2, 0, 2, 2])

In [172]:
#x_test values
y_test

array([3, 3, 3, 0, 1, 1, 3, 1, 1, 3])

In [289]:
from sklearn.metrics import mean_squared_error,r2_score
rscore=r2_score(y_test,y_prd)
r=rscore*100
print(r.round(),'%')

ValueError: Found input variables with inconsistent numbers of samples: [1, 10]

In [ ]:
#above image extracing method not worked properly so we using opencv image extracing method

In [260]:
#creating dataset with columns as we checked before
import pandas as pd
li1=[item for item in range(0,64)]
df=pd.DataFrame(columns=li1)
df

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]
Index: []

[0 rows x 64 columns]

In [261]:
#here we extracing the image as pixel by opencv
import cv2
import numpy as np
from sklearn.preprocessing import StandardScaler

fruits=['APPLE','BANANA','MANGO','GRAPHES']
labels=[]
column_names=df.columns
for i in fruits:
    for j in range(1,11):
        image = cv2.imread(r"C:\Users\Admin\PYTHON\Machine_Learning\Support vector Machine algorithm\FRUIT_IMAGES\{}\Image_{}.jpg".format(i,j))

        # Convert the image to grayscale
        gray_img = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

        # Threshold the image to create a binary image
        _, binary_img = cv2.threshold(gray_img, 127, 255, cv2.THRESH_BINARY)

        # Find contours in the binary image
        contours, _ = cv2.findContours(binary_img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        # Sort the contours by area and get the largest contour (assuming it's the number 3)
        contours = sorted(contours,key=cv2.contourArea, reverse=True)
        largest_contour = contours[0]

        # Get the bounding box of the largest contour
        x, y, w, h = cv2.boundingRect(largest_contour)

        # Crop the region of interest (ROI) containing the number 3
        number_three_roi = gray_img[y:y + h, x:x + w]

        # Resize the ROI to 8x8 pixels
        resized_roi = cv2.resize(number_three_roi, (8, 8))

        # Flatten the 2D array to a 1D array
        arr = resized_roi.flatten()

        # Reshape the 1D array to a 2D array with a single sample
        #arr_2d = arr.reshape(1, -1)
        label=i
        d={}
        index=len(df)
        for ii,jj in zip(column_names,arr):
            d.update({ii:jj})
        df.loc[index]=d
        labels.append(label)

In [262]:
df

0    1    2    3    4    5    6    7    8    9   ...   54   55   56   57  \
0   254  254  135  148  254  254  254  254  254  146  ...  111  254  253  253   
1   255  255   73  245  255  255  255  255  255  255  ...  255  255  255  255   
2   243  244  247  246  246  246  243  239  244  245  ...   63  224  240  234   
3   153  152  143  142  143  140  141  148  158  156  ...  185  180   87  133   
4   255  255  255  255  238  255  255  255  255  255  ...  251  255  255  255   
5   111  123  137  126  124  123  120  118  121  137  ...  117  155   74   77   
6     7   30  111  156  148  131   77   58   20   53  ...   92   64   90  100   
7    87   59  123  104  253  128  133   52  254   77  ...  165  115   88  149   
8    36   47   37   44  149  160  117   46   58   41  ...  139  131  115  131   
9   255  255  255  255  255  255  255  255  255  255  ...  198  247  255  255   
10  254  254  254  254  254  254  254  254  254  254  ...  254  254  254  254   
11  134  145   90  239  247   23   81   94  215  143  ...  158   21  194  136   
12  255  255  255  255  255  255  255  255  255  255  ...  255  255  255  255   
13  255  255  255  255  255  255  255  255  255  255  ...  255  255  255  246   
14  255  255   70  255  255  255  255  255  255  220  ...  251  255  255  255   
15  255  255  255  255  255  255  255  255  255  255  ...  250  255   85  255   
16  253  253  253  253  168  117  174  252  253  253  ...  253  253  253  253   
17  255  255  255  255  255  255  255  255  255  255  ...  203  191  255  255   
18  254  254  254  254  254  254  254  254  254  254  ...  254  254  254  254   
19  237  253  253  253  253  253  253  253   56  250  ...  250  253  160   65   
20  131  167  175  144  137   88   44   52   50  144  ...  139  142   56   79   
21  184  204  171  189  193   82  199   32  180   98  ...   76   20  115  128   
22  168  181  195  189  165  126  104  225  156  229  ...   97   55  203  113   
23   38  141   80  156   89  121  161  151  141  161  ...  171   91   79   29   
24  175  191  195  206  204  206  211  211  175  190  ...  241  237  190  189   
25  105  153  178  107  181  172  140   88  148  137  ...   84   47   76  102   
26  255  255  255  255  255  255  255  255  255  255  ...  255  255  255  255   
27  255  255  255  255  255  255  255  255  255  255  ...  251  255  255  255   
28  255  255  255  255  255  255  255  255  255  255  ...  254  255  255  255   
29  255  255  255  255  255  255  255  255  255  255  ...  255  255  255  255   
30  255  255  255  255  255  255  255  255  255  255  ...  134  255  255  255   
31   90  159  191  147  196  204  117   34  170  135  ...   40  156  166  207   
32  138   47  141   27   36  128   62   73   34  102  ...  186  199  199  181   
33  125  254  165  143  115  140  139  131  160  248  ...   86   85  105  128   
34  255  255  255  255  255  255  255  255  255  255  ...  255  255  255  255   
35  255  255  255  255  255  255  255  255  255  255  ...  254  255  255  251   
36  109  102   79  174   56  168   52  100  166  201  ...   85  149  250  254   
37   31   10   76  105  126  123  132  155  119  117  ...  160   36   62   98   
38  121  214  214  148  173  234  210  124   85  202  ...    6   25  252   13   
39   53   43   40    3    2   29    6  129   65   30  ...  112  222   99  133   

     58   59   60   61   62   63  
0   115  112  101   96  254  254  
1   255  137   29  249  255  255  
2   236  237  236  240  241  241  
3   165  160  174  184  192  182  
4   254  255  255  255  255  255  
5   103  108  108   91  146  174  
6   108   71  101  144   62   48  
7   144  118  127  106  116  128  
8   136  139  133  122  122  115  
9   253  246  244  250  252  255  
10  254  254  254  254  254  254  
11   30  232  161   33   36   77  
12  184  147  255  255  255  255  
13  159  136  141  239  255  255  
14  149  137  221  239  255  255  
15  241  225  220  227  252  255  
16   77  114  252  253  253  253  
17  252  255  255  255  255  255  
18  246  244   25 

In [249]:
#checking the whether dataset has null values or not
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
59    0
60    0
61    0
62    0
63    0
Length: 64, dtype: int64

In [263]:
#adding labels column to dataset
df['Labels']=labels

In [264]:
df

0    1    2    3    4    5    6    7    8    9  ...   55   56   57   58  \
0   254  254  135  148  254  254  254  254  254  146  ...  254  253  253  115   
1   255  255   73  245  255  255  255  255  255  255  ...  255  255  255  255   
2   243  244  247  246  246  246  243  239  244  245  ...  224  240  234  236   
3   153  152  143  142  143  140  141  148  158  156  ...  180   87  133  165   
4   255  255  255  255  238  255  255  255  255  255  ...  255  255  255  254   
5   111  123  137  126  124  123  120  118  121  137  ...  155   74   77  103   
6     7   30  111  156  148  131   77   58   20   53  ...   64   90  100  108   
7    87   59  123  104  253  128  133   52  254   77  ...  115   88  149  144   
8    36   47   37   44  149  160  117   46   58   41  ...  131  115  131  136   
9   255  255  255  255  255  255  255  255  255  255  ...  247  255  255  253   
10  254  254  254  254  254  254  254  254  254  254  ...  254  254  254  254   
11  134  145   90  239  247   23   81   94  215  143  ...   21  194  136   30   
12  255  255  255  255  255  255  255  255  255  255  ...  255  255  255  184   
13  255  255  255  255  255  255  255  255  255  255  ...  255  255  246  159   
14  255  255   70  255  255  255  255  255  255  220  ...  255  255  255  149   
15  255  255  255  255  255  255  255  255  255  255  ...  255   85  255  241   
16  253  253  253  253  168  117  174  252  253  253  ...  253  253  253   77   
17  255  255  255  255  255  255  255  255  255  255  ...  191  255  255  252   
18  254  254  254  254  254  254  254  254  254  254  ...  254  254  254  246   
19  237  253  253  253  253  253  253  253   56  250  ...  253  160   65  114   
20  131  167  175  144  137   88   44   52   50  144  ...  142   56   79    3   
21  184  204  171  189  193   82  199   32  180   98  ...   20  115  128  108   
22  168  181  195  189  165  126  104  225  156  229  ...   55  203  113   24   
23   38  141   80  156   89  121  161  151  141  161  ...   91   79   29  221   
24  175  191  195  206  204  206  211  211  175  190  ...  237  190  189  202   
25  105  153  178  107  181  172  140   88  148  137  ...   47   76  102   91   
26  255  255  255  255  255  255  255  255  255  255  ...  255  255  255  248   
27  255  255  255  255  255  255  255  255  255  255  ...  255  255  255  255   
28  255  255  255  255  255  255  255  255  255  255  ...  255  255  255  255   
29  255  255  255  255  255  255  255  255  255  255  ...  255  255  255  255   
30  255  255  255  255  255  255  255  255  255  255  ...  255  255  255  255   
31   90  159  191  147  196  204  117   34  170  135  ...  156  166  207   72   
32  138   47  141   27   36  128   62   73   34  102  ...  199  199  181  203   
33  125  254  165  143  115  140  139  131  160  248  ...   85  105  128   76   
34  255  255  255  255  255  255  255  255  255  255  ...  255  255  255  255   
35  255  255  255  255  255  255  255  255  255  255  ...  255  255  251  249   
36  109  102   79  174   56  168   52  100  166  201  ...  149  250  254  212   
37   31   10   76  105  126  123  132  155  119  117  ...   36   62   98  136   
38  121  214  214  148  173  234  210  124   85  202  ...   25  252   13   96   
39   53   43   40    3    2   29    6  129   65   30  ...  222   99  133  190   

     59   60   61   62   63   Labels  
0   112  101   96  254  254    APPLE  
1   137   29  249  255  255    APPLE  
2   237  236  240  241  241    APPLE  
3   160  174  184  192  182    APPLE  
4   255  255  255  255  255    APPLE  
5   108  108   91  146  174    APPLE  
6    71  101  144   62   48    APPLE  
7   118  127  106  116  128    APPLE  
8   139  133  122  122  115    APPLE  
9   246  244  250  252  255    APPLE  
10  254  254  254  254  254   BANANA  
11  232  161   33   36   77   BANANA  
12  147  255  255  255  255   BANANA  
13  136  141  239  255  255   BANANA  
14  137  221  239  255  255   BANANA  
15  225  220  227  252  255   BANANA  
16  114  252  253  25

In [273]:
#applying the standared scaler for pixel values
from sklearn.preprocessing import StandardScaler
lab1=StandardScaler()
X=lab1.fit_transform(df.iloc[:,:64])

In [274]:
#changing label column to numerical classification column
from sklearn.preprocessing import LabelEncoder
ell=LabelEncoder()
Y=ll.fit_transform(df['Labels'])

In [275]:
#seggregate the value to train and test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

In [276]:
#applying the SVM algorithm
from sklearn import svm
sv1=svm.SVC(kernel="rbf")
sv1.fit(X_train,Y_train)

SVC()

In [277]:
Y_test

array([3, 3, 3, 0, 1, 1, 3, 1, 1, 3])

In [278]:
predict=sv1.predict(X_test)

In [279]:
predict

array([2, 0, 2, 2, 1, 1, 1, 2, 2, 2])

In [280]:
from sklearn.metrics import mean_squared_error,r2_score
rscore=r2_score(Y_test,predict)
r=rscore*100
print(r.round(),'%')

-71.0 %


In [281]:
from sklearn import metrics
accuracy = metrics.accuracy_score(Y_test, predict)
print(f'Accuracy: {accuracy}')

Accuracy: 0.2


In [ ]:
#above both methods are not given good accuracy and prediction so we are using here hog method to extract the image

In [284]:
#hog-Histogram of Oriented Gradients 
#HOG is a popular technique for object detection and image classification. Let's break down the code
from skimage import feature
from skimage import color
from skimage import io

# Load an image (replace 'your_image_path' with the actual path)
image = io.imread(r"C:\Users\Admin\PYTHON\Machine_Learning\Support vector Machine algorithm\FRUIT_IMAGES\BANANA\Image_2.jpg")

# Convert the image to grayscale
gray_image = color.rgb2gray(image)

# Extract HOG features
hog_features1= feature.hog(gray_image, block_norm='L2-Hys')#This parameter specifies the normalization method for the blocks in the HOG calculation. In this case, it's set to 'L2', which means that each block of HOG features will be normalized using the L2-norm (Euclidean norm). Normalization is done to make the feature vector less sensitive to variations in illumination and contrast.

In [285]:
hog_features1

array([0., 0., 0., ..., 0., 0., 0.])

In [286]:
len(hog_features)

2373624

In [297]:
#creating the dataset with columns
import pandas as pd
li1=[item for item in range(0,2373624)]
dff=pd.DataFrame(columns=li1)
dff

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
Index: []

[0 rows x 2373624 columns]

In [301]:
#adding pixel values into the dataset from the directory image
fruits=['APPLE','BANANA','MANGO','GRAPHES']
labels=[]
column_names=dff.columns
for i in fruits:
    for j in range(1,11):
        image = io.imread(r"C:\Users\Admin\PYTHON\Machine_Learning\Support vector Machine algorithm\FRUIT_IMAGES\{}\Image_{}.jpg".format(i,j))
        gray_image = color.rgb2gray(image)

         # Extract HOG features
        hog_features = feature.hog(gray_image, block_norm='L2-Hys')
        label=i
        index=len(dff)
        dic={}
        for ii,jj in zip(hog_features,column_names):
            dic.update({jj:ii})
        dff.loc[index]=dic
        labels.append(label)

In [305]:
dff.fillna(0,inplace=True)

In [303]:
filled

In [306]:
dff

RecursionError: maximum recursion depth exceeded while calling a Python object

RecursionError: maximum recursion depth exceeded while calling a Python object