# NUMPY IN PYTHON

In [1]:
#numpy Array creation
import numpy
arr=numpy.array([12,56,76,44,56])
print(arr)
print(type(arr))

[12 56 76 44 56]
<class 'numpy.ndarray'>


In [2]:
#dtype-it's used to find datatype of numpy array
print(arr.dtype)

int32


In [4]:
#if we change one element ino float,all element will be change to float automatically
import numpy as np
arr1=np.array([56,34,23.6,57])
print(arr1)
print(type(arr1))
print(arr1.dtype)

[56.  34.  23.6 57. ]
<class 'numpy.ndarray'>
float64


In [5]:
#Create Numpy array with complex values
arr2=np.array([23,45,66,67+2j,90])
print(arr2)
print(type(arr2))
print(arr2.dtype)

[23.+0.j 45.+0.j 66.+0.j 67.+2.j 90.+0.j]
<class 'numpy.ndarray'>
complex128


In [7]:
#shape-it is used to find how many row and columns are present in Numpy array
print(arr2)
print(arr2.shape)

[23.+0.j 45.+0.j 66.+0.j 67.+2.j 90.+0.j]
(5,)


In [13]:
#ndim-it's used to find dimentional of array
from numpy import *
a=array(34)#
b=array([23,45,56,78])
c=array([[34,5667,89],[45,67,89]])
d=array([[[33,45,43],[345,67,65],[66,23,0]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
#changing list elements to Numpy array
list1=[45,56,55,43]
print(type(list1))
arr3=array(list1)
print(arr3)
print(type(arr3))

<class 'list'>
[45 56 55 43]
<class 'numpy.ndarray'>


In [15]:
#create Numpy array with string
arr4=array(['karthik','mani','ttth'])
print(arr4)
print(type(arr4))
print(arr4.dtype)

['karthik' 'mani' 'ttth']
<class 'numpy.ndarray'>
<U7


In [19]:
#size-it's going to find how much elements are present in Numpy array
#itemsize-it's going to find Byte size of array
print(arr4.size)
print(arr1)
print(arr1.itemsize)

3
[56.  34.  23.6 57. ]
8


In [26]:
#dtype declaration while creating numpyarray
arr5=array([45.0,6767.89],dtype="float")
print(arr5)
arr6=array(["k","karthki","frv"],dtype="str")
print(arr6)
arr7=array([34.6,56,21,23.6],dtype="int")#using this we can change the Datatype of element as we specified
print(arr7)
arr7=array([34.6,56,21,23.6],dtype="complex")
print(arr7)

[  45.   6767.89]
['k' 'karthki' 'frv']
[34 56 21 23]
[34.6+0.j 56. +0.j 21. +0.j 23.6+0.j]


In [28]:
#arange-using arange function we can give value till we need
import numpy as np
ar1=np.arange(10)
print(ar1)
print(type(ar1))
print(ar1.dtype)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int32


In [29]:
#append-using append we can add one or morethan one value into numpy array
ar1.append(78)#here wecan not add like list in python

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [33]:
#append-here we need to use numpy module and we should use variable to store additioanl element
print(ar1)
np.append(ar1,10)#if we not create variable,value not be add
print(ar1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [35]:
#append-here we need to use numpy module and we should use variable to store additioanl element
print(ar1)
new_element=np.append(ar1,10)#used new variable to add the element
print(new_element,type(new_element))

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


In [37]:
#using append adding more than one value
print(new_element)
new_element1=np.append(new_element,[11,12,13])
print(new_element1,type(new_element1))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13] <class 'numpy.ndarray'>


In [39]:
#Replacing element in numpy array
print(ar1)
ar1[0]=11
ar1[5]=55
print(ar1)

[0 1 2 3 4 5 6 7 8 9]
[11  1  2  3  4 55  6  7  8  9]


In [41]:
#insert-it is used to insert one element specific place into numpy array
print(ar1)
np.insert(ar1,1,22)#here also we need to use variable to add element
print(ar1)
print('*'*100)
print(ar1)
new_element2=np.insert(ar1,1,22)
print(new_element2)

[11  1  2  3  4 55  6  7  8  9]
[11  1  2  3  4 55  6  7  8  9]
****************************************************************************************************
[11  1  2  3  4 55  6  7  8  9]
[11 22  1  2  3  4 55  6  7  8  9]


In [43]:
#how to access Numpy Array elements using id
#slicing-fetch array element from where to where we want
print(ar1)
print(ar1[2])
print(ar1[1:])
print(ar1[-4:])
print(ar1[::-1])

[11  1  2  3  4 55  6  7  8  9]
2
[ 1  2  3  4 55  6  7  8  9]
[6 7 8 9]
[ 9  8  7  6 55  4  3  2  1 11]


In [46]:
#Array Value Operation
print(ar1)
#sum-to find Total Value of Array elements
#max-To find Biggest value from Array Elements
#min-To find smallest value from Array Elements
print(ar1.sum())
print(ar1.max())
print(ar1.min())

[11  1  2  3  4 55  6  7  8  9]
106
55
1


In [86]:
#Statiscal Operation
print(ar1)
#sqrt-what number multiplied by itself will equal to under the root of the number
#mean-Add all array elements and divide by no.of elemnts
#median-it will sorted center element .if center element is odd means,it add center element and next elemnt divide by 2.if center element is even,same number come as output
#std-
#exp-
print(np.sqrt(ar1))#defaulty it will give float format
print(np.mean(ar1))#defaulty it will give float format
print(np.median(ar1))#defaulty it will give float format
print(np.std(ar1))#defaulty it will give float format
print(np.exp(ar1))#defaulty it will give float format

[11  1  2  3  4 55  6  7  8  9]
[3.31662479 1.         1.41421356 1.73205081 2.         7.41619849
 2.44948974 2.64575131 2.82842712 3.        ]
10.6
6.5
15.107613974417006
[5.98741417e+04 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 7.69478527e+23 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [84]:
#sort-It is used to sort the elements to accending order
print(ar1)
print(np.sort(ar1))


[11  1  2  3  4 55  6  7  8  9]
[ 1  2  3  4  6  7  8  9 11 55]


In [94]:
#Arithemetic operations-using Arithemetic operatrs we can do add or sub or multiply or any other arithemetic operation with two arrays
ar2=np.arange(6,10)
ar3=np.arange(1,5)
ar4=np.arange(5,10)
print(ar2)
print(ar3)
print("Addition:",ar2+ar3)
print("Subtraction:",ar2-ar3)
print("Multiplication:",ar2*ar3)
print("Division:",ar2/ar3)
print("FloorDivision:",ar2//ar3)
print("Remainder:",ar2%ar3)
print("Expotential",ar2**ar3)

[6 7 8 9]
[1 2 3 4]
Addition: [ 7  9 11 13]
Subtraction: [5 5 5 5]
Multiplication: [ 6 14 24 36]
Division: [6.         3.5        2.66666667 2.25      ]
FloorDivision: [6 3 2 2]
Remainder: [0 1 2 1]
Expotential [   6   49  512 6561]


In [97]:
#zeros-eros package is used to add only Zero's in array.defaultly it will give float value
#ones-ones package is used to add only one's in array.defaultly it will give float value
#except Zero and one we can't add any other numbers like this
zeros=np.zeros(5)
ones=np.ones(7,dtype="int")
print(zeros)
print(zeros.dtype)
print(ones)
print(ones.dtype)
print(type(ones))

[0. 0. 0. 0. 0.]
float64
[1 1 1 1 1 1 1]
int32
<class 'numpy.ndarray'>


In [102]:
#astype-using this we can convert numpy array elements one datatype to another datatype
print(zeros)
print(zeros.dtype)
print('*'*50)
print(zeros.astype("complex"))
zeros2=zeros.astype("int")
print(zeros2)

[0. 0. 0. 0. 0.]
float64
**************************************************
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[0 0 0 0 0]


In [113]:
#eye-this function used to crate 2d array and columns and rows by we given value
ar4=np.eye(8)
ar5=np.eye(1)
print(ar4)
print(ar4.ndim)
print(ar5)
print(ar5.ndim)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
2
[[1.]]
2


In [128]:
#Creation of 2-dimensional array
arr_2d=np.array([[1,2,3,4,9],[8,9,0,7,9]])
print(arr_2d)
print(arr_2d.dtype)
print(arr_2d.ndim)
print(arr_2d.shape)#it will give row and colum of array
print(arr_2d.size)#it give output as total size of element in array
print(arr_2d.itemsize)#it give every array elements byte size

[[1 2 3 4 9]
 [8 9 0 7 9]]
int32
2
(2, 5)
10
4


In [122]:
#reshape and resize
#reshape-is used to create  how much rows and columns we need to create array
arr_rs=np.arange(12).reshape(3,4)#here we can give only which are the numbers multiply are equal to 12
print(arr_rs)
print(arr_rs.reshape(6,2))
arr_rs2=arr_rs.reshape(4,3)
print(arr_rs2)
print(arr_rs.reshape(6,6))#if we give more than 12, it will throw the error


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: cannot reshape array of size 12 into shape (6,6)

In [131]:
#resize -is help to fill the same values untill we met our mentioned dimention
arr_rs3=np.array([[34,67,77],[56,78,90]])
arr_rs4=np.resize(arr_rs3,(3,6))
print(arr_rs4)
print('*'*50)
print(arr_rs3)
print(np.resize(arr_rs3,(2,6)))

[[34 67 77 56 78 90]
 [34 67 77 56 78 90]
 [34 67 77 56 78 90]]
**************************************************
[[34 67 77]
 [56 78 90]]
[[34 67 77 56 78 90]
 [34 67 77 56 78 90]]


In [149]:
#creating a array to play on
from numpy import *
d_array=arange(12).reshape(4,3)
print(d_array,"Dimention:",d_array.ndim)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] Dimention: 2


In [163]:
#sum-find the sum of 2d array
#sum of all elements of an array
print(d_array.sum())#if we give sum,it will give whole elements sum value
print('*'*50)
#Sum along the row
print(d_array.sum(axis=0))#if we give sum(axis=0),it will give all row elements sum value
print('*'*50)
#sum along the column
print(d_array.sum(axis=1))#if we give sum(axis=1),it will give all column elements sum value
print('*'*50)


66
**************************************************
[18 22 26]
**************************************************
[ 3 12 21 30]
**************************************************
11


In [167]:
#Get Max and Min from 2d array
'''here |-row,--=column'''
print(d_array)
#max-find the maximum value from the array
#argmax-it's give Max or min element index position
print("*"*50)
print(d_array.max())#if we give max(),it will check all elements to find a max value
print("Index poition:",d_array.argmax())
print("*"*50)
print(d_array.max(axis=0))#if we give max(axis=0),it will check each row elements to find a max value from each row
print("Index poition:",d_array.argmax(axis=0))
print("*"*50)
print(d_array.max(axis=1))#if we give max(axis=1),it will check each column elements to find a max value from each column
print("Index poition:",d_array.argmax(axis=1))
print("*"*50)
print(d_array.min())#if we give min(),it will check all elements to find a min value
print("Index poition:",d_array.argmin())
print("*"*50)
print(d_array.min(axis=0))#if we give min(axis=0),it will check each row elements to find a min value from each row
print("Index poition:",d_array.argmin(axis=0))
print("*"*50)
print(d_array.min(axis=1))#if we give min(axis=1),it will check each column elements to find a min value from each column
print("Index poition:",d_array.argmax(axis=1))
print("*"*50)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
**************************************************
11
Index poition: 11
**************************************************
[ 9 10 11]
Index poition: [3 3 3]
**************************************************
[ 2  5  8 11]
Index poition: [2 2 2 2]
**************************************************
0
Index poition: 0
**************************************************
[0 1 2]
Index poition: [0 0 0]
**************************************************
[0 3 6 9]
Index poition: [2 2 2 2]
**************************************************


In [169]:
#some satistical function
#var-
#std-
sa_arr=arange(1,6)
print(sa_arr)
print(sa_arr.var())#varience
print(sa_arr.std())#standared deviation

[1 2 3 4 5]
2.0
1.4142135623730951


In [179]:
#numpy array Indexing and selection and slicing
#here we are going to fetch array element using index positions
ind_arr=arange(16).reshape(4,4)
print(ind_arr)
print("*"*50)
print(ind_arr[0])#if we give 0 position , it will give all 0 position row elements#[0]-row
print(ind_arr[1][1])#if we want to fetch specific one element means,we can use row and column#[1]-row,[1]-column
print(ind_arr[3][2])#[3]-row,[2]-column
print("*"*50)
#slicing-used to display elements where to where to we want
print(ind_arr[1:])#displaying all elements from 1 st row
print("*"*50)
print(ind_arr[1:,1:])
print("*"*50)
print(ind_arr[:2,:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
**************************************************
[0 1 2 3]
5
14
**************************************************
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
**************************************************
[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
**************************************************
[[0 1 2]
 [4 5 6]]


In [190]:
#changing the value of array as our wish
cha_arr=arange(1,6)
print(cha_arr)
print('*'*50)
cha_arr[0:3]=9#changing index position 0 to 3 all values 9
print(cha_arr)
print('*'*50)
# creating array with fetching values from another array
par=cha_arr[0:3]
print(par,type(par))
par2=cha_arr[3:5]
print(par2)
print('*'*50)
par[:]=55#[:]-means all element
print(par)
print('*'*50)
print(cha_arr)


[1 2 3 4 5]
**************************************************
[9 9 9 4 5]
**************************************************
[9 9 9] <class 'numpy.ndarray'>
[4 5]
**************************************************
[55 55 55]
**************************************************
[55 55 55  4  5]


In [206]:
#it is always safer to work on the copy of an original aray unless we really want to modify the original array
#copy-it is used to copy the original array elements
co_arr=arange(1,10).reshape(3,3)
print(co_arr)
print("*"*50)
copy_arr2=co_arr[0:2,:3].copy()
print(copy_arr2)
print("*"*50)
copy_arr=co_arr.copy()
print(copy_arr)
copy_arr[:]=11
print(copy_arr)
print("*"*50)
print(co_arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
**************************************************
[[1 2 3]
 [4 5 6]]
**************************************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 11 11]
 [11 11 11]
 [11 11 11]]
**************************************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [213]:
#selection-It is used to select the array elements using logical conditions
aa=array([23,56,4322,453,2,1,12],dtype="int")
print(aa)
print('*'*50)
#fething more than 100 elements using condition
aa>100#[false(23>100),false(56>100),true(4322>100),True(453>100),False(2>100),False(1>100),False(12>100)]
print('*'*50)
#how to fetch elements which are more than 100 elements(Not True or false value)
fetch=aa>100
print(fetch)
print(aa[fetch])#if we we declare like this,it give only true values

[  23   56 4322  453    2    1   12]
**************************************************
**************************************************
[False False  True  True False False False]
[4322  453]


In [136]:
#inside the 2d array one more array is called as 3d array
arrr=np.array([[[1,2,3]]])
print(arrr)
print(arrr.ndim)
arrrr=np.array([[[1,2,3],[3,45,6],[55,56,8]]])
print(arrrr)
print(arrrr.ndim)

[[[1 2 3]]]
3
[[[ 1  2  3]
  [ 3 45  6]
  [55 56  8]]]
3


In [214]:
#inside the 3d array one more array is called as 4d array
arrrr1=np.array([[[[1,2,3]]]])
print(arrrr1)
print(arrrr1.ndim)

[[[[1 2 3]]]]
4


In [89]:
#creating array with random
import numpy.random as np
np.random(10)#it's created 10 random numbers from 0 to 1


array([0.72996447, 0.10873607, 0.89390417, 0.85715425, 0.16508662,
       0.63233401, 0.02048361, 0.11673727, 0.31636731, 0.15791231])

In [91]:
#seed(random seed)-if every time run random value,it will change,by using seed we can stop changing random values every run
np.seed(11)#inside value is optional number we can give any value
np.random(10)

array([0.18026969, 0.01947524, 0.46321853, 0.72493393, 0.4202036 ,
       0.4854271 , 0.01278081, 0.48737161, 0.94180665, 0.85079509])

In [10]:
nn=np.random(5)
print(nn)
#n=np.random(1,3,4)#we can not give value like this
#print(n)

[0.69701955 0.34713549 0.15499692 0.62724321 0.1081592 ]


In [13]:
#randn-it will give the positive and negative floating point random value from 0 to 1
randn_arr=np.randn(9).reshape(3,3)
print(randn_arr)
print(type(randn_arr))
print(randn_arr.ndim)

[[ 0.1548027  -1.27669894 -0.7937275 ]
 [-0.90522501 -1.10408098 -0.34869934]
 [-0.24616903 -0.87887746 -1.44246514]]
<class 'numpy.ndarray'>
2


In [14]:
#sort-It's going to sort array elements in Accending order
randn_arr.sort()#if we not given any axis anything means,it sort all elements
print(randn_arr)

[[-1.27669894 -0.7937275   0.1548027 ]
 [-1.10408098 -0.90522501 -0.34869934]
 [-1.44246514 -0.87887746 -0.24616903]]


In [15]:
#sort(axis=0)-it will chane every row as a Accending order
randn_arr.sort(axis=0)
print(randn_arr)

[[-1.44246514 -0.90522501 -0.34869934]
 [-1.27669894 -0.87887746 -0.24616903]
 [-1.10408098 -0.7937275   0.1548027 ]]


In [16]:
#sort(axis=1)-it will chane every column as a Accending order
randn_arr.sort(axis=1)
print(randn_arr)

[[-1.44246514 -0.90522501 -0.34869934]
 [-1.27669894 -0.87887746 -0.24616903]
 [-1.10408098 -0.7937275   0.1548027 ]]


In [17]:
#randint-it generates random integers with in a specified range.it takes the lower and upper bounds as well as the dimensions of the output as Arguments
np.randint(1,5,8)#1-starting value,5-Ending value,8-No of elements

array([2, 4, 4, 1, 1, 2, 4, 2])

In [18]:
#Generate 2-d array of Shape (3,4) with random integers
ran_2d=np.randint(10,15,(3,4))#it's created 2-d array with random numbers as we given dimention
print(ran_2d)

[[11 12 13 10]
 [10 11 12 14]
 [12 12 10 13]]


In [20]:
#rand-it's like a random module to generate random numbers from 0 to 1
np.rand(15)

array([0.8406589 , 0.93719639, 0.98375968, 0.88466607, 0.9319849 ,
       0.6772331 , 0.10959231, 0.89322895, 0.19394196, 0.79508273,
       0.11041894, 0.24724478, 0.43342155, 0.18898907, 0.76194135])

In [26]:
#rand-creating 2-d array with radom numbers
np.rand(12).reshape(4,3)

array([[0.69883535, 0.31667955, 0.99866098],
       [0.56941727, 0.06124513, 0.02628768],
       [0.68508774, 0.66124916, 0.71996215],
       [0.44624133, 0.91722889, 0.3003879 ]])

In [25]:
np.random(12).reshape(4,3)

array([[0.22050168, 0.25377724, 0.782556  ],
       [0.89456886, 0.10764306, 0.64407134],
       [0.99111557, 0.36799904, 0.47589943],
       [0.86800327, 0.47444134, 0.48710003]])

In [28]:
#view(Shallow copying)-it is used to copy the original array to one more array(Duplicate) like a copy module but difference is if you change Duplicate array,same changes will applay to Original array also
import numpy as n
a=n.arange(5)
b=a.view()
print("Original Array:",a)
print("New Array:",b)
b[0]=100
print("Modification Arrays")
print("Original Array:",a)#here we can see changes has been applied original array also
print("New Array:",b)

Original Array: [0 1 2 3 4]
New Array: [0 1 2 3 4]
Modification Arrays
Original Array: [100   1   2   3   4]
New Array: [100   1   2   3   4]


In [34]:
#copy(Deep copying)-copy the original array to one more array but here if you do any change in copy array,it wont be apply in original array
c=n.arange(5)
d1=c.copy()
print("Original Array:",c)
print("New Array:",d1)
d1[0]=100
print("Modification Arrays")
print("Original Array:",c)#here we can see changes has not been applied original array
print("New Array:",d1)

Original Array: [0 1 2 3 4]
New Array: [0 1 2 3 4]
Modification Arrays
Original Array: [0 1 2 3 4]
New Array: [100   1   2   3   4]


In [38]:
#copy and view in 2d array
k1=n.arange(12).reshape(3,4)
k2=k1.copy()
print("Original Array:",k1)
print("New Array:",k2)
k2[0][1]=100
print("Modification Arrays")
print("Original Array:",k1)
print("New Array:",k2)
print("----------------------------")
k3=n.arange(12).reshape(3,4)
k4=k3.view()
print("Original Array:",k3)
print("New Array:",k4)
k4[0][1]=100
print("Modification Arrays")
print("Original Array:",k3)
print("New Array:",k4)

Original Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Modification Arrays
Original Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New Array: [[  0 100   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
----------------------------
Original Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Modification Arrays
Original Array: [[  0 100   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
New Array: [[  0 100   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [39]:
#python program to know the effects of any() and all() functions
a=n.array([1,2,3,0])
b=n.array([0,2,3,1])
c=a>b
print("Result of a>b:",c)#here we not given any() and all() so it's check all element of a and b
print("Check if any one element is true:",any(c))#here if any one is true,it will give result as true
print("Check if all element is true:",all(c))#here if any one is false,it will give result as false11
if (any(a>b)):
    print(' a contains atleast one element greater than those of b')

Result of a>b: [ True False False False]
Check if any one element is true: True
Check if all element is true: False
 a contains atleast one element greater than those of b


In [46]:
#A python progtam to understand the use of logical functions on arrays
ar1=n.array([1,2,3],int)
ar2=n.array([0,2,3],int)
And=n.logical_and(ar1>=0,ar2<4)#here it's give true when both condition are true
print(And)
Or=n.logical_or(ar2>=0,ar2==1)#here it's give true when any one condition is true
print(Or)
#logical_not
ar3=n.array([True,False,True,False])#it's give reverse result
Not1=n.logical_not(ar3)
print(Not1)
Not=n.logical_not(ar2)#here it giving output as if 0 is present,True.Other than 0 ,false
print(Not)
Not2=n.logical_not(ar1)
print(Not2)

[ True  True  True]
[ True  True  True]
[False  True False  True]
[ True False False]
[False False False]


In [53]:
#logical function in 2d array
ar4=n.array([[8,9,0],
           [89,45,6],
           [12,6,87]])
print(ar4.ndim)
lo_a=n.logical_and(ar4>=18,ar4<=88)
lo_o=n.logical_or(ar4>=18,ar4<=88)
lo_n=n.logical_not(ar4)
print(lo_a)
print(lo_o)
print(lo_n)

2
[[False False False]
 [False  True False]
 [False False  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False False  True]
 [False False False]
 [False False False]]


In [ ]:
#where-it is used to fetch array elements as we givien condition.
#Syntax:
#where(condition,expression1(variablename),expression2)

In [57]:
#where concept in Numpy
from numpy import *
ar=array([10,89,78,0,54])
even=where(ar%2==0,ar,' ')#it will fill we given third argument to condition false elements
print("Even numbers in array is:")
print(even)

Even numbers in array is:
['10' ' ' '78' '0' '54']


In [71]:
#fetching 0 elemets from two arrays by condition
ar1=array([90,78,34,0])
ar2=array([0,78,34,23])
w=where(ar1==0,ar1,'')
w1=where(ar2==0,ar2,'')
print(w,w1)

['' '' '' '0'] ['0' '' '' '']


In [72]:
#fetching only biggest elements from two arrays
ar1=array([90,78,34,0])
ar2=array([0,78,34,23])
w2=where(ar1>ar2,ar1,ar2)
print(w2)

[90 78 34 23]


In [74]:
#fetching element from 2d- array
d2=array([[32,56,6],
        [87,3,2],
        [67,8,8]])
print(d2.ndim)
w4=where(d2==8,d2,'')#fetching only 8
print(w4)

2
[['' '' '']
 ['' '' '']
 ['' '8' '8']]


In [112]:
#argwhere-this one give index value of given condition
aa=n.array(['kkk','utij','gbfn'])
print(type(aa))
se=argwhere(aa=='kkk')
print(se)
print("---------------------")
#2d array
aa1=arange(12).reshape(6,2)
print(aa1)
se1=argwhere(aa1>=10)
print(se1)

<class 'numpy.ndarray'>
[[0]]
---------------------
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[5 0]
 [5 1]]


In [76]:
#fill-it is used to fill we given value to array
arrr=arange(8)
print(arrr)
arrr.fill(4)#it's filled we given value 4 to all elements
print(arrr)

[0 1 2 3 4 5 6 7]
[4 4 4 4 4 4 4 4]


In [79]:
#using fill() in 2d array
arrr1=arange(10).reshape(5,2)
print(arrr1)
arrr1.fill(9)
print(arrr1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[9 9]
 [9 9]
 [9 9]
 [9 9]
 [9 9]]


In [86]:
#creating array with full
arrr2=n.full(shape=(4,2),fill_value=6)
print(arrr2)

[[6 6]
 [6 6]
 [6 6]
 [6 6]]


In [95]:
#creating array with string
cities=array(['Chennai','Tuticorin','Coimbatore','Tirchy'])
print(cities)

['Chennai' 'Tuticorin' 'Coimbatore' 'Tirchy']


In [96]:
#without print also we can show the array
cities

array(['Chennai', 'Tuticorin', 'Coimbatore', 'Tirchy'], dtype='<U10')

In [97]:
#String datatype
print(cities.dtype)#u10-means unicode character and maximum characterlength(coimbatorelength10)
#unicode character is nothing but it's a string

<U10


In [98]:
#sort the String array
cities.sort()
print(cities)

['Chennai' 'Coimbatore' 'Tirchy' 'Tuticorin']


In [102]:
#find the Unique value from the string array
cities4=array([['Chennai','Sivagangai','Tuticorin'],
             ['coimbatore','dindugal','madurai'],
             ['thirunelveli','madurai','tuticorin']])
c=unique(cities4)
print(c)

['Chennai' 'Sivagangai' 'Tuticorin' 'coimbatore' 'dindugal' 'madurai'
 'thirunelveli' 'tuticorin']


In [106]:
#it's fetched tuticorin two time cause one is T another one is t
#how to void above problem
#change whole array to lower
ch=n.char.lower(cities4)
print(ch)
#now we do unique
c1=unique(ch)
print('------------------------------------------')
print(c1)

[['chennai' 'sivagangai' 'tuticorin']
 ['coimbatore' 'dindugal' 'madurai']
 ['thirunelveli' 'madurai' 'tuticorin']]
------------------------------------------
['chennai' 'coimbatore' 'dindugal' 'madurai' 'sivagangai' 'thirunelveli'
 'tuticorin']


In [114]:
#dot matrix-it returns dot product of the Two vectors or matrixs
import numpy as np
a=np.array([[1,4],[5,6]])
b=np.array([[2,4],[5,2]])
print("Product of a and b is:")
print(a*b)
print("Dot Matrix of a and b is:")
print(np.dot(a,b))

Product of a and b is:
[[ 2 16]
 [25 12]]
Dot Matrix of a and b is:
[[22 12]
 [40 32]]


In [115]:
'''
Explanation:
[1  4   [2  4
 5  6]   5  2]
--------------
[1*2+4*5 [1*4+4*2
5*2+6*5] 5*4+6*2]
---------------------
[22  12
40   32]
'''

'\nExplanation:\n[1  4   [2  4\n 5  6]   5  2]\n--------------\n[1*2+4*5 [1*4+4*2\n5*2+6*5] 5*4+6*2]\n---------------------\n[22  12\n40   32]\n'

In [118]:
#dot matrix
aa=np.array([2,4,3])
aa2=np.array([[5,6],[3,1],[2,5]])
print(aa)
print(aa2)
print("--------------------")
d=np.dot(aa,aa2)
print(d)

[2 4 3]
[[5 6]
 [3 1]
 [2 5]]
[28 31]


In [ ]:
'''
Explanation:
[2 4 3] [5  6
         3  1
         2  5]
[2*5+4*3+3*2  2*6+4*1+3*5]
[28  31]
'''

In [6]:
#3d array-Inside 2d array one more array 3d array
import numpy as np
d_arr=np.array([[['k','rr','gb'],['rf','dd','d'],['aa','ac','cc']]])
print(d_arr)
print(d_arr.dtype)
print(d_arr.ndim)
print(d_arr.shape)#(1,3,3)-1=Size of array,3=row,3=column

[[['k' 'rr' 'gb']
  ['rf' 'dd' 'd']
  ['aa' 'ac' 'cc']]]
<U2
3
(1, 3, 3)


In [10]:
print(d_arr.reshape(3,3,1))

[[['k']
  ['rr']
  ['gb']]

 [['rf']
  ['dd']
  ['d']]

 [['aa']
  ['ac']
  ['cc']]]


In [9]:
d_arr2=np.arange(12).reshape(3,2,2)
print(d_arr2)
print(d_arr2.dtype)
print(d_arr2.ndim)
print(d_arr2.shape)#(3,2,2)-3=Size of array,2=row,2=column

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
int32
3
(3, 2, 2)


In [12]:
#transpose-It is used to change row elements to column
a0=np.arange(9).reshape(3,3)
print("Normal Array:")
print(a0)
print("After Transpose:")
print(np.transpose(a0))

Normal Matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After Transpose:
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [23]:
#matrix -matrix is nothing array only we call matrix in maths
#instead of using array function we can use matrix function to create new array
#using matrix creating 2d array
mat=np.matrix('[4,6;3,8]')
print(mat)
print(type(mat))
print(mat.ndim)
print('-----------------')
#matrix only support for 2d array not 3d and 1d
mat1=np.matrix('[[[4,63,8;78,56,4]]]')
print(mat1)
print(type(mat1))
print(mat1.ndim)
print('-----------------')
#transpose
print(np.transpose(mat))

[[4 6]
 [3 8]]
<class 'numpy.matrix'>
2
-----------------
[[ 4 63  8]
 [78 56  4]]
<class 'numpy.matrix'>
2
-----------------
[[4 3]
 [6 8]]


In [29]:
#hstack(Horizontal stack)-it will make array elements as horizontal----
#if we give one array means,it will change like this
print(mat)
print(np.hstack(mat))
print("------------------")
#if we give two arrays means,it will change like This
array_hstack=np.arange(8).reshape(2,4)
array_hstack2=np.matrix('23,8,89,0;98,6,5,4')
print("Array's is:")
print(array_hstack)
print(array_hstack2)
print("hstack Array's is:")
hstack_array=np.hstack((array_hstack,array_hstack2))
print(hstack_array)

[[4 6]
 [3 8]]
[[4 6 3 8]]
------------------
Array's is:
[[0 1 2 3]
 [4 5 6 7]]
[[23  8 89  0]
 [98  6  5  4]]
hstack Array's is:
[[ 0  1  2  3 23  8 89  0]
 [ 4  5  6  7 98  6  5  4]]


In [32]:
#vstack(Vertical stack)-it will display array in vertical order|
#if we give one array means,it will change like this
print(mat)
print(np.vstack(mat))
print("------------------")
#if we give two arrays means,it will change like This
array_vstack=np.arange(10).reshape(2,5)
array_vstack2=np.matrix('23,8,89,78,0;98,6,5,4,89')
print("Array's is:")
print(array_vstack)
print(array_vstack2)
print("vstack Array's is:")
vstack_array=np.vstack((array_vstack,array_vstack2))
print(vstack_array)

[[4 6]
 [3 8]]
[[4 6]
 [3 8]]
------------------
Array's is:
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[23  8 89 78  0]
 [98  6  5  4 89]]
vstack Array's is:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [23  8 89 78  0]
 [98  6  5  4 89]]


In [41]:
#Arithemetic operation in 2d-array
print(array_vstack)
print(array_vstack2)
print(array_vstack.ndim)
print(array_vstack2.ndim)
print("---------------")
print("Addition:\n",array_vstack+array_vstack2)
print("---------------")
print("Subtraction:\n",array_vstack-array_vstack2)
print("---------------")
#print("Multiplication:\n",array_vstack*array_vstack2)
print("---------------")
print("Division:\n",array_vstack/array_vstack2)
print("---------------")
print("Floor Division:\n",array_vstack//array_vstack2)
print("---------------")
print("Modules:\n",array_vstack%array_vstack2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[23  8 89 78  0]
 [98  6  5  4 89]]
2
2
---------------
Addition:
 [[ 23   9  91  81   4]
 [103  12  12  12  98]]
---------------
Subtraction:
 [[-23  -7 -87 -75   4]
 [-93   0   2   4 -80]]
---------------
---------------
Division:
 [[0.         0.125      0.02247191 0.03846154        inf]
 [0.05102041 1.         1.4        2.         0.1011236 ]]
---------------
Floor Division:
 [[0 0 0 0 0]
 [0 1 1 2 0]]
---------------
Modules:
 [[0 1 2 3 0]
 [5 0 2 0 9]]


C:\Users\Admin\AppData\Local\Temp\ipykernel_3260\1722399197.py:13: RuntimeWarning: divide by zero encountered in divide
  print("Division:\n",array_vstack/array_vstack2)
C:\Users\Admin\AppData\Local\Temp\ipykernel_3260\1722399197.py:15: RuntimeWarning: divide by zero encountered in floor_divide
  print("Floor Division:\n",array_vstack//array_vstack2)
C:\Users\Admin\AppData\Local\Temp\ipykernel_3260\1722399197.py:17: RuntimeWarning: divide by zero encountered in remainder
  print("Modules:\n",array_vstack%array_vstack2)


In [61]:
#homework-Python program to accept matrix(array) from the keyboard and display it's transpose,dot matrix methods
#getting input from user to create two dimensiona array
print("Creation Of 2-D Array")
row=int(input("Enter the Row of array:"))
column=int(input("Enter the Column of array:"))
row_l=[]
for i in range(row):
    row_ll=[]
    for j in range(column):
        element=int(input(f'Enter the number of [{i}] [{j}]:'))
        row_ll.append(element)
    row_l.append(row_ll)
user_2d=np.array(row_l)
#getting input from user to create two dimensiona array
print("Creation Of 1-D Array")
size=int(input("Enter the Size of array:"))
row_1d=[]
for i in range(size):
    element=int(input(f'Enter the number of [{i}]:'))
    row_1d.append(element)
user_1d=np.array(row_1d)
print("1D-Array is:\n",row_1d)
print(type(user_1d))
print(user_1d.ndim)
print("1D-Array is:\n",user_2d)
print(type(user_2d))
print(user_2d.ndim)
print("Transpose Array is:\n",np.transpose(user_2d))
print("Transpose Array is:\n",np.dot(user_2d,user_1d))#3*6+4*5+5*4=58
                                                      #6*6+7*5+8*4=71+32=103

Creation Of 2-D Array
Enter the Row of array:2
Enter the Column of array:3
Enter the number of [0] [0]:3
Enter the number of [0] [1]:4
Enter the number of [0] [2]:5
Enter the number of [1] [0]:6
Enter the number of [1] [1]:7
Enter the number of [1] [2]:8
Creation Of 1-D Array
Enter the Size of array:3
Enter the number of [0]:6
Enter the number of [1]:5
Enter the number of [2]:4
1D-Array is:
 [6, 5, 4]
<class 'numpy.ndarray'>
1
1D-Array is:
 [[3 4 5]
 [6 7 8]]
<class 'numpy.ndarray'>
2
Transpose Array is:
 [[3 6]
 [4 7]
 [5 8]]
Transpose Array is:
 [ 58 103]


In [54]:
#creating 3-d array by user input
depth=int(input("Enter the Depth of array:"))
row2=int(input("Enter the Row of array:"))
column2=int(input("Enter the Column of array:"))
row_l2=[]
for k in range(depth):
    row_ll3=[]
    for i in range(row2):
        row_ll2=[]
        for j in range(column2):
            element=int(input(f'Enter the number of [{i}] [{j}]:'))
            row_ll2.append(element)
        row_ll3.append(row_ll2)
    row_l2.append(row_ll3)
user2_2d=np.array(row_l2)
print(user2_2d)
print(type(user2_2d))
print(user2_2d.ndim)

Enter the Depth of array:3
Enter the Row of array:2
Enter the Column of array:2
Enter the number of [0] [0]:4
Enter the number of [0] [1]:4
Enter the number of [1] [0]:5
Enter the number of [1] [1]:5
Enter the number of [0] [0]:6
Enter the number of [0] [1]:6
Enter the number of [1] [0]:7
Enter the number of [1] [1]:7
Enter the number of [0] [0]:8
Enter the number of [0] [1]:8
Enter the number of [1] [0]:9
Enter the number of [1] [1]:9
[[[4 4]
  [5 5]]

 [[6 6]
  [7 7]]

 [[8 8]
  [9 9]]]
<class 'numpy.ndarray'>
3


In [65]:
# Numpy linspace-it is used to create a numpy array whose elements are equally spaced between start and end
#Defaultly 50 elements will be generated
np.linspace(5,10)#it's generated random one time values from 5 to 10.5-startvale,10-endvalue
#here we have not given no of elements,so defaultly it given 50 elements.

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [64]:
print(np.linspace(5,10,5))#last 5 is no of elements

[ 5.    6.25  7.5   8.75 10.  ]


In [69]:
#creating 2d array using linspace
aaaa=np.linspace(start=(1,8),stop=(8,8),num=3,dtype=int)#num=3-no of rows
print(aaaa)

[[1 8]
 [4 8]
 [8 8]]


In [72]:
#creating 2d array using linspace
aaaa1=np.linspace(start=(1,6),stop=(8,9),num=5,dtype=complex)#num=5-no of rows
print(aaaa1)
print('---------------')
aaaa2=np.linspace(start=6,stop=9,num=5,dtype=int)#num=5-no of rows
print(aaaa2)

[[1.  +0.j 6.  +0.j]
 [2.75+0.j 6.75+0.j]
 [4.5 +0.j 7.5 +0.j]
 [6.25+0.j 8.25+0.j]
 [8.  +0.j 9.  +0.j]]
---------------
[6 6 7 8 9]


In [73]:
#numpy logspace-it is used to create a numpy array whose elements are equally spaced between start and end on logerithmic scale(log base 10)
#Defaultly 50 elements will be generated
np.logspace(8,20)#not given no of elements so its generated 50 elements

array([1.00000000e+08, 1.75751062e+08, 3.08884360e+08, 5.42867544e+08,
       9.54095476e+08, 1.67683294e+09, 2.94705170e+09, 5.17947468e+09,
       9.10298178e+09, 1.59985872e+10, 2.81176870e+10, 4.94171336e+10,
       8.68511374e+10, 1.52641797e+11, 2.68269580e+11, 4.71486636e+11,
       8.28642773e+11, 1.45634848e+12, 2.55954792e+12, 4.49843267e+12,
       7.90604321e+12, 1.38949549e+13, 2.44205309e+13, 4.29193426e+13,
       7.54312006e+13, 1.32571137e+14, 2.32995181e+14, 4.09491506e+14,
       7.19685673e+14, 1.26485522e+15, 2.22299648e+15, 3.90693994e+15,
       6.86648845e+15, 1.20679264e+16, 2.12095089e+16, 3.72759372e+16,
       6.55128557e+16, 1.15139540e+17, 2.02358965e+17, 3.55648031e+17,
       6.25055193e+17, 1.09854114e+18, 1.93069773e+18, 3.39322177e+18,
       5.96362332e+18, 1.04811313e+19, 1.84206997e+19, 3.23745754e+19,
       5.68986603e+19, 1.00000000e+20])

In [74]:
np.logspace(8,20,5)

array([1.e+08, 1.e+11, 1.e+14, 1.e+17, 1.e+20])

In [76]:
#create 2-d array using logspace
sss=np.logspace(start=(8,9),stop=(9,9),num=4,dtype=int)
print(sss)

[[ 100000000 1000000000]
 [ 215443469 1000000000]
 [ 464158883 1000000000]
 [1000000000 1000000000]]


In [93]:
#round-it is used to round the floating point value
import numpy as np
Fahrenheit=np.array([0.,12.,45.21,34.,99.91,32.])
fahrenheit_to_centigrate=(Fahrenheit-32)*5/9
print(fahrenheit_to_centigrate)
print(np.round(fahrenheit_to_centigrate))#if we give round it will give remove all . after value
print(np.round(fahrenheit_to_centigrate,2))#if we want .after two values,we can give 2

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778
   0.        ]
[-18. -11.   7.   1.  38.   0.]
[-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [95]:
#isin()-it is used to check both arrays has same values or not.if same values means,give true.not same values means give false
import numpy as np
arr=np.array([67,78,90])
arr2=np.array([78,90,56])
result=arr==arr2#we can use comparison operator to check but it will give true when both same values position same and
print(result)   #it's not work when both array size are not same
print(np.isin(arr,arr2))#arr compare with arr2.while comparing values are equal it give true otherwise give false

[False False False]
[False  True  True]


In [98]:
#isin
ar=np.array(['kk','gg','ggg','wee'])
ar1=np.array(['kk','wee'])
result=np.isin(ar,ar1)
print(result)
result1=np.isin('gg',ar)#even we can give like this also
print(result1)

[ True False False  True]
True


In [117]:
#intersect1d-which is used to fetch common values from two arrays
#union1d-it is used to fetch unique values from both arrays
#setdiff1d-(difference)it is compare two arrays and give non-duplicate value from first array
#setxor1d-(Symmetric difference)it is display all unique values from two arrays
import numpy as np
print(arr)
print(arr2)
print("------------------")
print("Union:\n",np.union1d(arr,arr2))
print("Intersection:\n",np.intersect1d(arr,arr2))
print("Difference:\n",np.setdiff1d(arr,arr2))
print("Symmetric_differnce:\n",np.setxor1d(arr,arr2))

[67 78 90]
[78 90 56]
------------------
Union:
 [56 67 78 90]
Intersection:
 [78 90]
Difference:
 [67]
Symmetric_differnce:
 [56 67]


In [120]:
#for 2-d array also 1d only
ar=np.arange(6).reshape(3,2)
ar2=np.arange(5,11).reshape(2,3)
print(ar)
print(ar2)
print("------------------")
print("Union:\n",np.union1d(ar,ar2))
print("Intersection:\n",np.intersect1d(ar,ar2))
print("Difference:\n",np.setdiff1d(ar,ar2))
print("Symmetric_differnce:\n",np.setxor1d(ar,ar2))

[[0 1]
 [2 3]
 [4 5]]
[[ 5  6  7]
 [ 8  9 10]]
------------------
Union:
 [ 0  1  2  3  4  5  6  7  8  9 10]
Intersection:
 [5]
Difference:
 [0 1 2 3 4]
Symmetric_differnce:
 [ 0  1  2  3  4  6  7  8  9 10]


In [127]:
#pad()-Padding means adding elements with specified values to the boundaries of the array, 
#Syntax-numpy.pad(array, pad_width, mode, **kwargs)
#array-existing array
#pad_width=if we give 2 means,bofore and after it's add rwo columns
#mode-it's describe mode of filling.there are different modes available(constant,minimum,edge,symmetric,mean,median)
import numpy as np
sa=np.arange(12).reshape(3,4)
print("Original:")
print(sa)
print("Constant:")
pad=np.pad(sa,pad_width=1,mode='constant',constant_values=0)#mode constaant fill we given value as border
print(pad)
print("Edge:")
pad1=np.pad(sa,pad_width=2,mode='edge')#mode edge fill last value of array as border
print(pad1)
print("Minimum:")
pad2=np.pad(sa,pad_width=1,mode='minimum')#mode minimum fill minimum value of array as border
print(pad2)
print("mean:")
pad3=np.pad(sa,pad_width=1,mode='mean')#mode mean fill by average value of array as border
print(pad3)
print("Median:")
pad3=np.pad(sa,pad_width=1,mode='median')#mode median fill by center value of array as border
print(pad3)

Original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Constant:
[[ 0  0  0  0  0  0]
 [ 0  0  1  2  3  0]
 [ 0  4  5  6  7  0]
 [ 0  8  9 10 11  0]
 [ 0  0  0  0  0  0]]
Edge:
[[ 0  0  0  1  2  3  3  3]
 [ 0  0  0  1  2  3  3  3]
 [ 0  0  0  1  2  3  3  3]
 [ 4  4  4  5  6  7  7  7]
 [ 8  8  8  9 10 11 11 11]
 [ 8  8  8  9 10 11 11 11]
 [ 8  8  8  9 10 11 11 11]]
Minimum:
[[ 0  0  1  2  3  0]
 [ 0  0  1  2  3  0]
 [ 4  4  5  6  7  4]
 [ 8  8  9 10 11  8]
 [ 0  0  1  2  3  0]]
mean:
[[ 6  4  5  6  7  6]
 [ 2  0  1  2  3  2]
 [ 6  4  5  6  7  6]
 [10  8  9 10 11 10]
 [ 6  4  5  6  7  6]]
Median:
[[ 6  4  5  6  7  6]
 [ 2  0  1  2  3  2]
 [ 6  4  5  6  7  6]
 [10  8  9 10 11 10]
 [ 6  4  5  6  7  6]]


In [130]:
#title()-it is used to repeat full array as we want 
sample_array=np.array([1,2,3,4])
repeat=np.tile(sample_array,2)#no of time repeat value
print(repeat)
print('-----------------------')
#2d-array
sample_array1=np.array([[1,2,3,4],[67,90,87,0]])
repeat1=np.tile(sample_array1,3)#no of time repeat value
print(repeat1)

[1 2 3 4 1 2 3 4]
-----------------------
[[ 1  2  3  4  1  2  3  4  1  2  3  4]
 [67 90 87  0 67 90 87  0 67 90 87  0]]


In [137]:
#just tiling specfic element
sample_array1=np.array([[1,2,3,4],[67,90,87,0]])
repeat1=np.tile(sample_array1[0,3],3)#no of time repeat value
print(repeat1)

[4 4 4]


In [134]:
#repeat()-it is used to repeat each element as we want
sample_array=np.array([1,2,3,4])
repeat=np.repeat(sample_array,2)
print(repeat)
#2d-array
sample_array1=np.array([[1,2,3,4],[67,90,87,0]])
repeat1=np.repeat(sample_array1,3)#no of time repeat value
print(repeat1)

[1 1 2 2 3 3 4 4]
[ 1  1  1  2  2  2  3  3  3  4  4  4 67 67 67 90 90 90 87 87 87  0  0  0]


In [138]:
#just repeating specfic element
sample_array1=np.array([[1,2,3,4],[67,90,87,0]])
repeat1=np.repeat(sample_array1[0,3],3)#no of time repeat value
print(repeat1)

[4 4 4]


In [141]:
#real()-It's helps to seperate real number from complex data value array
#imag()-It's helps to seperate Imaginary number from complex data value array
compl=np.array([34,67,89,8],dtype=complex)
print(compl)
print("--------------------------")
print("Seperated it Real number:\n",np.real(compl))
imag=np.imag(compl)
print("Seperated it Imaginary number:\n",imag)

[34.+0.j 67.+0.j 89.+0.j  8.+0.j]
--------------------------
Seperated it Real number:
 [34. 67. 89.  8.]
Seperated it Imaginary number:
 [0. 0. 0. 0.]


In [17]:
#lexsort()-it is used to sort the elements in accending order and gives elements index position.
#while sorting if two elements are same it sort by one more mentioned key array value
#example array b two times 8's are there.so it will check key array(a array) equal elemnet.8--6,8--23 so it sort first 8--6 
import numpy as np
a=np.array([34,0,6,23,1,4])
b=np.array([4,67,8,8,7,6])
sort=np.lexsort((a,b))#it will sort second parameter(b),first one key array
print(sort)

[0 5 4 2 3 1]


In [31]:
#lexsort()
a=np.array([['a','b','z','d'],['e','f','g','h']])
b=np.array([['a','o','a','a'],['a','m','o','m']])
so=np.lexsort((a,b),axis=-1)
print(so)

[[0 3 2 1]
 [0 1 3 2]]
