# Numpy-Excersices

his notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the NumPy documentation.

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
dim1=np.array([3,4,5,6])
# Create a 2-dimensional NumPy array using np.array()
dim2=np.array([[3,4,5,6],[4,5,4,3]])
# Create a 3-dimensional Numpy array using np.array()
dim3=np.array([[[3,4,5,6],[5,6,5,3]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print("Shape of the array:",dim1.shape)
print("number of dimensions:",dim1.ndim)
print("Data type of array:",dim1.dtype)
print("size of array:",dim1.size)
print("itemsize of array:",dim1.itemsize)
print("type of array:",type(dim1))

Shape of the array: (4,)
number of dimensions: 1
Data type of array: int32
size of array: 4
itemsize of array: 4
type of array: <class 'numpy.ndarray'>


In [6]:
# Attributes of 2-dimensional array
print("Shape of the array:",dim2.shape)
print("number of dimensions:",dim2.ndim)
print("Data type of array:",dim2.dtype)
print("size of array:",dim2.size)
print("itemsize of array:",dim2.itemsize)
print("type of array:",type(dim2))

Shape of the array: (2, 4)
number of dimensions: 2
Data type of array: int32
size of array: 8
itemsize of array: 4
type of array: <class 'numpy.ndarray'>


In [7]:
# Attributes of 3-dimensional array
print("Shape of the array:",dim3.shape)
print("number of dimensions:",dim3.ndim)
print("Data type of array:",dim3.dtype)
print("size of array:",dim3.size)
print("itemsize of array:",dim3.itemsize)
print("type of array:",type(dim3))

Shape of the array: (1, 2, 4)
number of dimensions: 3
Data type of array: int32
size of array: 8
itemsize of array: 4
type of array: <class 'numpy.ndarray'>


In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(dim2)
df

0  1  2  3
0  3  4  5  6
1  4  5  4  3

In [13]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2),dtype=int)
print(ones)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [14]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3),dtype=int)
print(zeros)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [15]:
# Create an array within a range of 0 and 100 with step 3
arr=np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [22]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
ra=np.random.randint(0,10,(7,2))
print(ra)

[[1 0]
 [0 7]
 [7 9]
 [3 3]
 [2 3]
 [4 4]
 [3 8]]


In [18]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
ra2=np.random.random((3,5))
ra2

array([[0.84594177, 0.42289417, 0.59792562, 0.20096558, 0.95938054],
       [0.5005404 , 0.12035607, 0.58184066, 0.81460162, 0.05722313],
       [0.65520243, 0.0669872 , 0.04472583, 0.88513608, 0.00226396]])

In [29]:
# Set the random seed to 42
np.random.seed(5)
# Create a random array of numbers between 0 & 10 of size (4, 6)
ra3=np.random.randint(0,10,24).reshape(4,6)
print(ra3)

[[3 6 6 0 9 8]
 [4 7 0 0 7 1]
 [5 7 0 1 4 6]
 [2 9 9 9 9 1]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

because we used seed function right

In [36]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
ra4=np.random.randint(1,10,(3,7))
print(ra4)
print('-'*50)
# Find the unique numbers in the array you just created
print("Unique Numbers:",np.unique(ra4))

[[6 4 5 1 3 3 2]
 [2 8 2 8 3 7 4]
 [7 9 1 2 1 9 8]]
--------------------------------------------------
Unique Numbers: [1 2 3 4 5 6 7 8 9]


In [37]:
# Find the 0'th index of the latest array you created
ra4[0]

array([6, 4, 5, 1, 3, 3, 2])

In [39]:
# Get the first 2 rows of latest array you created
ra4[0:2]

array([[6, 4, 5, 1, 3, 3, 2],
       [2, 8, 2, 8, 3, 7, 4]])

In [43]:
# Get the first 2 values of the first 2 rows of the latest array
ra4[:2,:2]

array([[6, 4],
       [2, 8]])

In [41]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
aa=np.random.randint(0,10,(3,5))
aa2=np.random.randint(0,10,(3,5))
print(aa)
print(aa2)

[[7 9 4 1 4]
 [2 1 7 5 4]
 [2 2 1 2 3]]
[[1 2 4 9 0]
 [1 2 3 8 5]
 [5 4 3 9 5]]


In [42]:
# Add the two arrays together
print(aa+aa2)

[[ 8 11  8 10  4]
 [ 3  3 10 13  9]
 [ 7  6  4 11  8]]


In [44]:
# Create another array of ones of shape (5, 3)
aa3=np.arange(15).reshape(5,3)
aa3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [57]:
# Try add the array of ones and the other most recent array together
one=np.ones((3,5),dtype=int)
add=one+aa3
add

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [47]:
#reshaped array
one=np.ones((5,3),dtype=int)
add=one+aa3
add

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [51]:
# Create another array of ones of shape (3, 5)
arr3=np.array([[3,5,6,7,3],[34,6,2,1,2],[0,2,31,6,77]])
print(arr3.shape)
print(arr3)

(3, 5)
[[ 3  5  6  7  3]
 [34  6  2  1  2]
 [ 0  2 31  6 77]]


In [60]:
# Subtract the new array of ones from the other most recent array
add1=add.reshape(3,5)
print("1st array:\n",add1.reshape(3,5))
print("2nd array:\n",arr3)
print("Subtract:\n",add1-arr3)

1st array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2nd array:
 [[ 3  5  6  7  3]
 [34  6  2  1  2]
 [ 0  2 31  6 77]]
Subtract:
 [[ -2  -3  -3  -3   2]
 [-28   1   6   8   8]
 [ 11  10 -18   8 -62]]


In [61]:
# Multiply the ones array with the latest array
print("1st array:\n",add1.reshape(3,5))
print("2nd array:\n",arr3)
print("Multiply:\n",add1*arr3)

1st array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2nd array:
 [[ 3  5  6  7  3]
 [34  6  2  1  2]
 [ 0  2 31  6 77]]
Multiply:
 [[   3   10   18   28   15]
 [ 204   42   16    9   20]
 [   0   24  403   84 1155]]


In [62]:
# Take the latest array to the power of 2 using '**'
print("Latest array:\n",arr3)
print("power of 2 using '**':\n",arr3**2)

Latest array:
 [[ 3  5  6  7  3]
 [34  6  2  1  2]
 [ 0  2 31  6 77]]
power of 2 using '**':
 [[   9   25   36   49    9]
 [1156   36    4    1    4]
 [   0    4  961   36 5929]]


In [64]:
# Do the same thing with np.square()
print("Latest array:\n",arr3)
print("Squre of:\n",np.square(arr3))

Latest array:
 [[ 3  5  6  7  3]
 [34  6  2  1  2]
 [ 0  2 31  6 77]]
Squre of:
 [[   9   25   36   49    9]
 [1156   36    4    1    4]
 [   0    4  961   36 5929]]


In [65]:
# Find the mean of the latest array using np.mean()
print("Latest array:\n",arr3)
print("mean value:\n",np.mean(arr3))

Latest array:
 [[ 3  5  6  7  3]
 [34  6  2  1  2]
 [ 0  2 31  6 77]]
mean value:
 12.333333333333334


In [66]:
# Find the maximum of the latest array using np.max()
print("Latest array:\n",arr3)
print("Maximum value:\n",np.max(arr3))

Latest array:
 [[ 3  5  6  7  3]
 [34  6  2  1  2]
 [ 0  2 31  6 77]]
Maximum value:
 77


In [67]:
# Find the minimum of the latest array using np.min()
print("Latest array:\n",arr3)
print("Minimum value:\n",np.min(arr3))

Latest array:
 [[ 3  5  6  7  3]
 [34  6  2  1  2]
 [ 0  2 31  6 77]]
Minimum value:
 0


In [68]:
# Find the standard deviation of the latest array
print("Latest array:\n",arr3)
print("Standared Deviation:\n",np.std(arr3))

Latest array:
 [[ 3  5  6  7  3]
 [34  6  2  1  2]
 [ 0  2 31  6 77]]
Standared Deviation:
 19.96218647565664


In [69]:
# Find the variance of the latest array
print("Latest array:\n",arr3)
print("variance value:\n",np.var(arr3))

Latest array:
 [[ 3  5  6  7  3]
 [34  6  2  1  2]
 [ 0  2 31  6 77]]
variance value:
 398.48888888888894


In [70]:
# Reshape the latest array to (3, 5, 1)
print("Latest array:\n",arr3)
print("reshaped array:\n",arr3.reshape(3,5,1))

Latest array:
 [[ 3  5  6  7  3]
 [34  6  2  1  2]
 [ 0  2 31  6 77]]
reshaped array:
 [[[ 3]
  [ 5]
  [ 6]
  [ 7]
  [ 3]]

 [[34]
  [ 6]
  [ 2]
  [ 1]
  [ 2]]

 [[ 0]
  [ 2]
  [31]
  [ 6]
  [77]]]


In [71]:
# Transpose the latest array
print("Latest array:\n",arr3)
print("Transpose array:\n",np.transpose(arr3))

Latest array:
 [[ 3  5  6  7  3]
 [34  6  2  1  2]
 [ 0  2 31  6 77]]
Transpose array:
 [[ 3 34  0]
 [ 5  6  2]
 [ 6  2 31]
 [ 7  1  6]
 [ 3  2 77]]


What does the transpose do?
it's changed array row as column

In [78]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array1=np.random.uniform(0,10,(3,3)).astype(int)
array2=np.random.uniform(0,10,(3,2)).astype(int)
print(array1)
print(array2)

[[5 4 8]
 [2 6 4]
 [4 8 3]]
[[4 1]
 [0 6]
 [8 6]]


In [79]:
# Perform a dot product on the two newest arrays you created
print("Dot matrix:\n",np.dot(array1,array2))

Dot matrix:
 [[84 77]
 [40 62]
 [40 70]]


In [80]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array3=np.random.randint(0,10,(4,3))
array4=np.random.randint(0,10,(4,3))
print(array3)
print(array4)

[[1 8 6]
 [1 5 1]
 [8 8 8]
 [3 3 9]]
[[7 0 8]
 [7 3 4]
 [7 0 6]
 [3 1 5]]


In [81]:
# Perform a dot product on the two newest arrays you created
print("Dot matrix:\n",np.dot(array3,array4))

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

# It doesn't work. How would you fix it?
Why it's not working means for matrix multiplication first array row shape and second array column shape should be same.
by transpose the array,we can fix 

In [84]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
print("Dot matrix:\n",np.dot(array3,array4.T))#.T-transpose

Dot matrix:
 [[ 55  55  43  41]
 [ 15  26  13  13]
 [120 112 104  72]
 [ 93  66  75  57]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on np.dot() may help, as well as reading Math is Fun's guide on the dot product.

Let's now compare arrays.

In [93]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array5=np.random.randint(0,10,(3,4))
array6=np.random.randint(0,10,(3,4))
print(array5)
print(array6)

[[4 5 3 9]
 [9 5 4 1]
 [9 2 0 3]]
[[6 7 4 3]
 [3 7 3 1]
 [9 5 8 9]]


In [94]:
# Compare the two arrays with '>'
print("Compare Two arrays:",array5>array6)

Compare Two arrays: [[False False False  True]
 [ True False  True False]
 [False False False False]]


What happens when you compare the arrays with >?
Its compared two arrays elements by we given condition.if condtion is true,given true.if condition is false,given false

In [95]:
# Compare the two arrays with '>='
print("first array:\n",array5)
print("second array:\n",array6)
print("Compare Two arrays:",array5>=array6)

first array:
 [[4 5 3 9]
 [9 5 4 1]
 [9 2 0 3]]
second array:
 [[6 7 4 3]
 [3 7 3 1]
 [9 5 8 9]]
Compare Two arrays: [[False False False  True]
 [ True False  True  True]
 [ True False False False]]


In [98]:
# Find which elements of the first array are greater than 7
print("first array:\n",array5)
print("greater than 7:\n",array5>7)
con=array5>7
print("elements of Greater than 7:\n",array5[con])

first array:
 [[4 5 3 9]
 [9 5 4 1]
 [9 2 0 3]]
greater than 7:
 [[False False False  True]
 [ True False False False]
 [ True False False False]]
elements of Greater than 7:
 [9 9 9]


In [100]:
# Which parts of each array are equal? (try using '==')
print("first array:\n",array5)
print("second array:\n",array6)
print("Each array equal:",array5==array6)

first array:
 [[4 5 3 9]
 [9 5 4 1]
 [9 2 0 3]]
second array:
 [[6 7 4 3]
 [3 7 3 1]
 [9 5 8 9]]
Each array equal: [[False False False False]
 [False False False  True]
 [ True False False False]]


In [103]:
# Sort one of the arrays you just created in ascending order
print("first array:\n",array5)
print("sorted array:\n",np.sort(array5))

first array:
 [[3 4 5 9]
 [1 4 5 9]
 [0 2 3 9]]
sorted array:
 [[3 4 5 9]
 [1 4 5 9]
 [0 2 3 9]]


In [104]:
# Sort the indexes of one of the arrays you just created
print("first array:\n",array5)
print("indexces of sorted array:\n",np.argsort(array5))

first array:
 [[3 4 5 9]
 [1 4 5 9]
 [0 2 3 9]]
indexces of sorted array:
 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [106]:
# Find the index with the maximum value in one of the arrays you've created
print("first array:\n",array5)
print("maximum value:\n",np.max(array5))
print("index of maximum value:\n",np.argmax(array5))

first array:
 [[3 4 5 9]
 [1 4 5 9]
 [0 2 3 9]]
maximum value:
 9
index of maximum value:
 3


In [107]:
# Find the index with the minimum value in one of the arrays you've created
print("first array:\n",array5)
print("minimum value:\n",np.min(array5))
print("index of minimum value:\n",np.argmin(array5))

first array:
 [[3 4 5 9]
 [1 4 5 9]
 [0 2 3 9]]
minimum value:
 0
index of minimum value:
 8


In [109]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
print("first array:\n",array5)
print(" maximum value:\n",np.max(array5,axis=1))
print("index of maximum value:\n",np.argmax(array5,axis=1))

first array:
 [[3 4 5 9]
 [1 4 5 9]
 [0 2 3 9]]
 maximum value:
 [9 9 9]
index of maximum value:
 [3 3 3]


In [110]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
print("first array:\n",array5)
print(" minimum value:\n",np.min(array5,axis=0))
print("index of minimum value:\n",np.argmin(array5,axis=0))

first array:
 [[3 4 5 9]
 [1 4 5 9]
 [0 2 3 9]]
 minimum value:
 [0 2 3 9]
index of minimum value:
 [2 2 2 0]


In [116]:
# Create an array of normally distributed random numbers
mean=0
std_div=1
na=np.random.normal(mean,std_div,(4,2))
print(na)

[[-0.59332312 -0.24009104]
 [ 1.32005045 -0.26919013]
 [-1.91602589 -1.97121562]
 [ 0.41810678  0.70930993]]


In [114]:
# Create an array with 10 evenly spaced numbers between 1 and 100
lin_array=np.linspace(1,100,10)
print(lin_array)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
