# NUMPY QUESTIONS:

In [8]:
#1. Write a NumPy program to print the NumPy version on your system.
import numpy
print("NUMPY VERSION:",numpy.__version__)

NUMPY VERSION: 1.23.5


In [11]:
'''
2. Write a NumPy program to convert a list of numeric values into a onedimensional NumPy array.
Expected Output:
Original List: [19.23, 15.62, 100, 56.32]
One-dimensional NumPy array: [ 19.23 15.62 100. 56.32]
'''
import numpy as np
List_Values=[19,23,15,62,100,56,32]
Array_form_List=np.array([List_Values])
print("1-D Array is:\n",Array_form_List)
print(type(Array_form_List))

1-D Array is:
 [[ 19  23  15  62 100  56  32]]
<class 'numpy.ndarray'>


In [14]:
'''
3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 
10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]
'''
matrix_3=np.arange(2,11).reshape(3,3)
print("3*3 matrix is:\n",matrix_3)

3*3 matrix is:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [16]:
'''
4. Write a NumPy program to create a null vector of size 10 and update the 
sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.
'''
null_vector=np.zeros(10)
print("NULL Vector is:\n",null_vector)
null_vector[6]=11
print("Updated_null_vector is:\n",null_vector)

NULL Vector is:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated_null_vector is:
 [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [17]:
'''
5. Write a NumPy program to create an array with values ranging from 12 to 
38.
Expected Output:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 
36 37
'''
create_array=np.arange(12,38)
print("Expected Output:\n",create_array)

Expected Output:
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [22]:
'''
6. Write a NumPy program to reverse an array (the first element becomes the 
last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 
36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 
13 12]
'''
print("Original array:\n",create_array)
sorted_array=sorted(create_array,reverse=True)
print("Reverse array:\n",sorted_array)

Original array:
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
 [37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12]


In [24]:
'''
7. Write a NumPy program to convert an array to a floating type.
Sample output:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]
'''
original_array=np.array([1,2,3,4])
print("Original array:\n",original_array)
converted_float=original_array.astype(float)
print("Array converted to a float type:\n",converted_float)

Original array:
 [1 2 3 4]
Array converted to a float type:
 [1. 2. 3. 4.]


In [121]:
'''
8. Write a NumPy program to create a 2D array with 1 on the border and 0 
inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
'''
o_array=np.ones((5,5))
print("Original array:\n",o_array)
#o_array[1:,1:]=0
#o_array[4]=1
o_array[1:-1,1:-1]=0#1:-1-from index 1 to -2
'''
    1:-1 for the rows means you're selecting all rows except the first and the last.
    1:-1 for the columns means you're selecting all columns except the first and the last.
'''
print("1 on the border and 0 inside in the array:\n",o_array)

Original array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [155]:
'''
9. Write a NumPy program to add a border (filled with 0's) around an existing 
array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
...........
[ 0. 0. 0. 0. 0.]]
'''
ooo_array=np.ones((3,3))
print("Original array:\n",ooo_array)
pad=np.pad(ooo_array,pad_width=1,mode="constant",constant_values=0)
print("Result:\n",pad)

Original array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Result:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [85]:
'''
10. Write a NumPy program to create an 8x8 matrix and fill it with a 
checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
'''
resz=np.zeros((8,8),dtype=int)
resz[1::2, ::2] = 1#1::2-fetch odd index row,::2-fetch even index column
resz[::2,1::2] = 1#::2-fetch even index row,:1::2-fetch odd index column
print(resz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
'''
11. Write a NumPy program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]
'''
List=[78,89,7,3,4]
Tuple=((7,9,9,0),(89,6,9,0))
print(List)
print(Tuple)
print('-------------------------')
List_To_Array=np.array(List)
Tuple_To_Array=np.array(Tuple)
print("List to array:\n",List_To_Array)
print("Tuple to array:\n",Tuple_To_Array)
print(Tuple_To_Array.ndim)
print(Tuple_To_Array.dtype)
print(type(Tuple_To_Array))

[78, 89, 7, 3, 4]
((7, 9, 9, 0), (89, 6, 9, 0))
-------------------------
List to array:
 [78 89  7  3  4]
Tuple to array:
 [[ 7  9  9  0]
 [89  6  9  0]]
2
int32
<class 'numpy.ndarray'>


In [31]:
'''
12. Write a NumPy program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]
'''
Original_array=np.array([10,20,30])
print("Original array:\n",Original_array)
After_append=np.append(Original_array,[40,50,60,70,80,90])
print("After append values to the end of the array:\n",After_append)

Original array:
 [10 20 30]
After append values to the end of the array:
 [10 20 30 40 50 60 70 80 90]


In [34]:
'''
13. Write a NumPy program to create a 5x5x5 cube of 1's.
Expected Output:
[[[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]]
............
[[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]]]

'''
cube_of_1s=np.ones(125,dtype=int).reshape(5,5,5)
print("Expected Output:\n",cube_of_1s)

Expected Output:
 [[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [17]:
'''
14. Write a NumPy program to convert Centigrade degrees into Fahrenheit 
degrees. Centigrade values are stored in a NumPy array.
Sample Array [0, 12, 45.21, 34, 99.91]
[-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]
Expected Output:
Values in Fahrenheit degrees:
[ 0. 12. 45.21 34. 99.91 32. ]
Values in Centigrade degrees:
[-17.78 -11.11 7.34 1.11 37.73 0. ]
Values in Centigrade degrees:
[-17.78 -11.11 7.34 1.11 37.73 0. ]
Values in Fahrenheit degrees:
[-0. 12. 45.21 34. 99.91 32. ]

'''
import numpy as np
Fahrenheit=np.array([0.,12.,45.21,34.,99.91,32.])
Centigrade=np.array([-17.78,-11.11,7.34,1.11,37.73,0.])#centigrade is celcius
print("Fahrenheit Value is:\n",Fahrenheit)
print("Centigrade Value is:\n",Centigrade)
Centigrade_to_fahrenheit=(Centigrade*9/5)+32
print("Centigrade_to_fahrenheit is:\n",np.round(Centigrade_to_fahrenheit,2))
fahrenheit_to_centigrate=(Fahrenheit-32)*5/9
print("fahrenheit_to_centigrate is:\n",np.round(fahrenheit_to_centigrate,2))

Fahrenheit Value is:
 [ 0.   12.   45.21 34.   99.91 32.  ]
Centigrade Value is:
 [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Centigrade_to_fahrenheit is:
 [-0.   12.   45.21 34.   99.91 32.  ]
fahrenheit_to_centigrate is:
 [-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [184]:
'''
15. Write a NumPy program to find the real and imaginary parts of an array of 
complex numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]
'''
og_array=np.array([[ 1.00000000+0.j,0.70710678+0.70710678j]])
print("Original Array:\n",og_array)
print("------------------------------------------------------------")
print("Real part of the array:\n",np.real(og_array))
print("Imaginary part of the array:\n",np.imag(og_array))

Original Array:
 [[1.        +0.j         0.70710678+0.70710678j]]
------------------------------------------------------------
Real part of the array:
 [[1.         0.70710678]]
Imaginary part of the array:
 [[0.         0.70710678]]


In [166]:
'''
16. Write a NumPy program to find the number of elements in an array. It also 
finds the length of one array element in bytes and the total bytes consumed by 
the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24
'''
aaa=np.array([3.,90.6,56.])
print("Array:\n",aaa)
print("--------------------------------")
print("Size of the array:\n",aaa.size)#total element of array
print("Length of one array element in bytes:\n",aaa.itemsize)#1 elemnt byte size of array
print("Total bytes consumed by the elements of the array:\n",aaa.size*aaa.itemsize)

Array:
 [ 3.  90.6 56. ]
--------------------------------
Size of the array:
 3
Length of one array element in bytes:
 8
Total bytes consumed by the elements of the array:
 24


In [39]:
'''
17. Write a NumPy program to test whether each element of a 1-D array is 
also present in a second array.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [0, 40]
Compare each element of array1 and array2
[ True False False True False]
'''
Array1=np.array([0,10,20,40,60])
Array2=np.array([0,40])
print("Array1 is:\n",Array1)
print("Array2 is:\n",Array2)
compare=np.isin(Array1,Array2)
print("Compare each element of array1 and array2:\n",compare)

Array1 is:
 [ 0 10 20 40 60]
Array2 is:
 [ 0 40]
Compare each element of array1 and array2:
 [ True False False  True False]


In [40]:
'''
18. Write a NumPy program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]
'''
Array1=np.array([0,10,20,40,60])
Array2=np.array([10,30,40])
print("Array1 is:\n",Array1)
print("Array2 is:\n",Array2)
compare=np.intersect1d(Array1,Array2)
print("Compare each element of array1 and array2:\n",compare)

Array1 is:
 [ 0 10 20 40 60]
Array2 is:
 [10 30 40]
Compare each element of array1 and array2:
 [10 40]


In [43]:
'''
19. Write a NumPy program to get the unique elements of an array.
Expected Output:
Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
[2 3]]
Unique elements of the above array:
[1 2 3]

'''
import numpy as np
original_array=np.array([10,10,20,20,30,30])
original_array1=np.array([[1,1],[2,3]])
print(original_array)
print(original_array1)
print("-------------------------------")
print("Unique elements of the above array:\n",np.unique(original_array))
print("Unique elements of the above array:\n",np.unique(original_array1))
print("--------------------------------")
#if we need to find out unique elemnt from two arrys,we can use union
print("Unique elemnts from two arrays:\n",np.union1d(original_array,original_array1))

[10 10 20 20 30 30]
[[1 1]
 [2 3]]
-------------------------------
Unique elements of the above array:
 [10 20 30]
Unique elements of the above array:
 [1 2 3]
--------------------------------
Unique elemnts from two arrays:
 [ 1  2  3 10 20 30]


In [45]:
'''
20. Write a NumPy program to find the set difference between two arrays. The 
set difference will return sorted, distinct values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]
'''
import numpy as np
array1=np.array([ 0,10,20,40,60,80])
array2=np.array([10, 30, 40, 50, 70, 90])
print("Array1:\n",array1)
print("Array2:\n",array2)
print("------------------------")
print("Set difference between two arrays:\n",np.setdiff1d(array1,array2))

Array1:
 [ 0 10 20 40 60 80]
Array2:
 [10 30 40 50 70 90]
------------------------
Set difference between two arrays:
 [ 0 20 60 80]


In [47]:
'''
21. Write a NumPy program to find the set exclusive-or of two arrays. Set 
exclusive-or will return sorted, distinct values in only one (not both) of the input 
arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]'''
print("Array1:\n",array1)
print("Array2:\n",array2)
print("------------------------")
print("Unique values that are in only one (not both) of the input arrays:\n",np.setxor1d(array1,array2))

Array1:
 [ 0 10 20 40 60 80]
Array2:
 [10 30 40 50 70 90]
------------------------
Unique values that are in only one (not both) of the input arrays:
 [ 0 20 30 50 60 70 80 90]


In [48]:
'''
22. Write a NumPy program to find the union of two arrays. Union will return a 
unique, sorted array of values in each of the two input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique sorted array of values that are in either of the two input arrays:
[ 0 10 20 30 40 50 60 70 80]
'''
print("Array1:\n",array1)
print("Array2:\n",array2)
print("------------------------")
print("Unique sorted array of values that are in either of the two input arrays:\n",np.union1d(array1,array2))

Array1:
 [ 0 10 20 40 60 80]
Array2:
 [10 30 40 50 70 90]
------------------------
Unique sorted array of values that are in either of the two input arrays:
 [ 0 10 20 30 40 50 60 70 80 90]


In [181]:
'''
23. Write a NumPy program to test whether all elements in an array evaluate 
to True.
Note: 0 evaluates to False in NumPy.
'''
#if 0 not comes,it will give True result
arrr = np.array([1, 2, 3, 7, 4])
res=np.all(arrr)
print(res)
print("--------------------------")
#if 0 comes,it will give false result
arrr1 = np.array([1, 2, 3, 0, 4])
res1=arrr1.all()
print(res1)

True
--------------------------
False


In [180]:
'''
24. Write a NumPy program to test whether any array element along a given 
axis evaluates to True.
Note: 0 evaluates to False in NumPy.
'''
#if 0 not comes,it will give True result
arrr = np.array([1, 2, 3, 7, 4])
res=np.any(arrr)
print(res)
print("--------------------------")
#if 0 comes also ,it will give true result.cause here one case is pass means it give true only
arrr1 = np.array([1, 2, 3, 0, 4])
res1=np.any(arrr1)
print(res1)
#if all values 0,it will result false
arrr2 = np.array([0,0,0,0,0])
res2=arrr2.any()
print(res2)

True
--------------------------
True
False


In [169]:
'''
25. Write a NumPy program to construct an array by repeating.
Sample array: [1, 2, 3, 4]
Expected Output:
Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]
'''
sample_array=np.array([1,2,3,4])
print("Sample Array:\n",sample_array)
print("Repeating 2 times:\n",np.tile(sample_array,2))
repeat_3=np.tile(sample_array,3)
print("Repeating 3 times:\n",repeat_3)

Sample Array:
 [1 2 3 4]
Repeating 2 times:
 [1 2 3 4 1 2 3 4]
Repeating 3 times:
 [1 2 3 4 1 2 3 4 1 2 3 4]


In [172]:
'''
26.Write a NumPy program to repeat array elements.
Expected Output:
[3 3 3 3]
[1 1 2 2 3 3 4 4]
'''
print("Original Array:\n",sample_array)
print("Expected Output:")
print(np.repeat(sample_array[2],4))
print(np.repeat(sample_array,2))

Original Array:
 [1 2 3 4]
Expected Output:
[3 3 3 3]
[1 1 2 2 3 3 4 4]


In [53]:
'''
27. Write a NumPy program to find the indices of the maximum and minimum 
values along the given axis of an array.
Original array: [1 2 3 4 5 6]
Maximum Values: 5
Minimum Values: 0
'''
orig_array=np.arange(1,7)
print("Original array:\n",orig_array)
print("------------------------------")
print("Maximum Values:",orig_array.max())
print("Minimum Values:",orig_array.min())

Original array:
 [1 2 3 4 5 6]
------------------------------
Maximum Values: 6
Minimum Values: 1


In [18]:
'''
28. Write a NumPy program to compare two arrays using NumPy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
'''
import numpy as np
a=np.array([1,2])
b=np.array([4,5])
print("Array a:\n",a)
print("Array b:\n",b)
print("-------------------")
print('a>b:\n',a>b)
print('a>=b:\n',a>=b)
print('a<b:\n',a<b)
print('a<=b:\n',a<=b)

Array a:
 [1 2]
Array b:
 [4 5]
-------------------
a>b:
 [False False]
a>=b:
 [False False]
a<b:
 [ True  True]
a<=b:
 [ True  True]


In [68]:
'''
29. Write a NumPy program to sort along the first and last axes of an array.
Sample array: [[2,5],[4,4]]
Expected Output:
Original array:
[[4 6]
[2 1]]
Sort along the first axis:
[[2 1]
[4 6]]
Sort along the last axis:
[[1 2]
[4 6]]
'''
oo_array=np.array([[4,6],[2,1]])
print("Original array:\n",oo_array)
print("------------------------------")
nn=np.sort(oo_array,axis=0)
print("Sort along the first axis:\n",nn)
print("Sort along the last axis:\n",np.sort(nn,axis=1))
print("------------------------------")
print("Original array:\n",oo_array)#after sort also original array has not changed


Original array:
 [[4 6]
 [2 1]]
------------------------------
Sort along the first axis:
 [[2 1]
 [4 6]]
Sort along the last axis:
 [[1 2]
 [4 6]]
------------------------------
Original array:
 [[4 6]
 [2 1]]


In [1]:
'''
30. Write a NumPy program to sort pairs of a first name and a last name and 
return their indices (first by last name, then by first name).
first_names = (Betsey, Shelley, Lanell, Genesis, Margery)
last_names = (Battle, Brien, Plotner, Stahl, Woolum)
Expected Output:
[1 3 2 4 0]
'''
import numpy as np
first_names=np.array(['Betsey', 'Shelley','Lanell','Genesis','Margery'])
last_names = np.array(['Battle','Brien','Stahl', 'Woolum','Plotner'])
s=np.lexsort((first_names,last_names))
print(s)

[0 1 4 2 3]


In [3]:
sorted_names = [(first_names[i], last_names[i]) for i in s]
print(sorted_names)


[('Betsey', 'Battle'), ('Shelley', 'Brien'), ('Margery', 'Plotner'), ('Lanell', 'Stahl'), ('Genesis', 'Woolum')]
