# Spam message prediction project

In [718]:
#import the libraries
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [719]:
#read the dataset spam.csv dataset
dd=pd.read_csv('spam.csv')

In [720]:
dd.head()#displaying first 5 rows

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [721]:
dd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [722]:
dd.shape

(5572, 2)

In [723]:
#Encoding or changing string column into float using encoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(dd[['Message']])

In [724]:
x#more data's that why it's giving compressed format

<5572x5157 sparse matrix of type '<class 'numpy.float64'>'
	with 5572 stored elements in Compressed Sparse Row format>

In [725]:
x1=x.toarray()#changed to compressed format to array

In [726]:
x1.shape

(5572, 5157)

In [727]:
x1[1:40]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [728]:
#split the dataset as train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x1,dd['Category'].values,test_size=0.25,random_state=0)

In [729]:
x_train[0:5]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [730]:
x_test[0:10]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [731]:
# applying standared scaler
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
x_train=st.fit_transform(x_train)
x_test=st.fit_transform(x_test)

In [732]:
#applying the Logistic regression algorithm
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(random_state=0)
lr.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [733]:
#predict the message 
y_prd=lr.predict(x_test)

In [734]:
y_prd[50:150]

array(['ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham'], dtype=object)

In [741]:
#testing by user input
test=dd['Message'][2]
test

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

# Encoding the text meassage and creating array with 5157 values

In [742]:
from keras.preprocessing.text import Tokenizer

# Your message
#message = "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

# Create a Tokenizer with a fixed vocabulary size
max_words = 5157
tokenizer = Tokenizer(num_words=max_words, char_level=True)

# Fit the tokenizer on the text
tokenizer.fit_on_texts([test])

# Transform the text into a sequence of integers
sequence = tokenizer.texts_to_sequences([test])

# Convert the sequence to a binary matrix (one-hot encoding)
encoded_array = tokenizer.sequences_to_matrix(sequence, mode='freq')

# Print the resulting array
print(encoded_array)


[[0.         0.17419355 0.10322581 ... 0.         0.         0.        ]]


In [743]:
test2=st.fit_transform(encoded_array)
test2

array([[0., 0., 0., ..., 0., 0., 0.]])

In [744]:
lr.predict(encoded_array)#it has predicted wrong because we had given spam meassage but it's showing ham

array(['ham'], dtype=object)

In [747]:
lr.predict_proba(test2)

array([[0.99727981, 0.00272019]])

In [641]:
#why it's happending means,category columns has most of the ham messages

In [545]:
dd['Category'].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [580]:
#now what we going to do,we creating new dataset with 500 ham and 500 spam by old dataset
dd1=dd[dd['Category']=='ham']

In [582]:
dd1=dd1.head(500)

In [583]:
dd1

Category                                            Message
0        ham  Go until jurong point, crazy.. Available only ...
1        ham                      Ok lar... Joking wif u oni...
3        ham  U dun say so early hor... U c already then say...
4        ham  Nah I don't think he goes to usf, he lives aro...
6        ham  Even my brother is not like to speak with me. ...
..       ...                                                ...
577      ham  I'm tired of arguing with you about this week ...
578      ham                Ü wait 4 me in sch i finish ard 5..
580      ham  Arngd marriage is while u r walkin unfortuntly...
581      ham  Huh so early.. Then ü having dinner outside iz...
582      ham     Ok anyway no need to change with what you said

[500 rows x 2 columns]

In [584]:
dd2=dd[dd['Category']=='spam']

In [585]:
dd2=dd2.head(500)

In [586]:
dd2

Category                                            Message
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
5        spam  FreeMsg Hey there darling it's been 3 week's n...
8        spam  WINNER!! As a valued network customer you have...
9        spam  Had your mobile 11 months or more? U R entitle...
11       spam  SIX chances to win CASH! From 100 to 20,000 po...
...       ...                                                ...
3742     spam                                      2/2 146tf150p
3750     spam  Dear Voucher Holder 2 claim your 1st class air...
3755     spam  Bloomberg -Message center +447797706009 Why wa...
3758     spam  YES! The only place in town to meet exciting a...
3763     spam  FREE for 1st week! No1 Nokia tone 4 ur mob eve...

[500 rows x 2 columns]

In [591]:
dd3=pd.concat([dd1,dd2],ignore_index=True)#it will ignore the index position and join both dataset

In [592]:
dd3

Category                                            Message
0        ham  Go until jurong point, crazy.. Available only ...
1        ham                      Ok lar... Joking wif u oni...
2        ham  U dun say so early hor... U c already then say...
3        ham  Nah I don't think he goes to usf, he lives aro...
4        ham  Even my brother is not like to speak with me. ...
..       ...                                                ...
995     spam                                      2/2 146tf150p
996     spam  Dear Voucher Holder 2 claim your 1st class air...
997     spam  Bloomberg -Message center +447797706009 Why wa...
998     spam  YES! The only place in town to meet exciting a...
999     spam  FREE for 1st week! No1 Nokia tone 4 ur mob eve...

[1000 rows x 2 columns]

In [606]:
#Encoding or changing string column into float using encoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct1=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder="passthrough")
X=ct1.fit_transform(dd3[['Message']])

In [607]:
X

<1000x941 sparse matrix of type '<class 'numpy.float64'>'
	with 1000 stored elements in Compressed Sparse Row format>

In [608]:
X=X.toarray()

In [630]:
X.shape

(1000, 941)

In [692]:
#split the dataset as train and test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,dd3['Category'].values,test_size=0.25,random_state=1)

In [693]:
# applying standared scaler
from sklearn.preprocessing import StandardScaler
st1=StandardScaler()
X_train=st1.fit_transform(X_train)
X_test=st1.fit_transform(X_test)

In [694]:
#applying the Logistic regression algorithm
from sklearn.linear_model import LogisticRegression
lr1=LogisticRegression(random_state=1)
lr1.fit(X_train,Y_train)

LogisticRegression(random_state=1)

In [695]:
Y_prd=lr1.predict(X_test)

In [686]:
Y_prd[50:150]

array(['ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam',
       'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham',
       'ham'], dtype=object)

In [754]:
#testing by user input
text=dd3['Message'][520]
text

'URGENT! Your Mobile No. was awarded £2000 Bonus Caller Prize on 5/9/03 This is our final try to contact U! Call from Landline 09064019788 BOX42WR29C, 150PPM'

In [755]:
#encoding the message with 941 column value value 
from keras.preprocessing.text import Tokenizer
max_words=941
token=Tokenizer(num_words=941,char_level=True)
token.fit_on_texts([text])
seq=token.texts_to_sequences([text])
t_array=token.sequences_to_matrix(seq,mode='freq')#'freq': This mode represents the frequency of each token in the sequence.
print(t_array)

[[0.         0.16025641 0.06410256 0.05769231 0.05128205 0.05128205
  0.05128205 0.05128205 0.03846154 0.03846154 0.03846154 0.03205128
  0.03205128 0.02564103 0.02564103 0.01923077 0.01923077 0.01923077
  0.01923077 0.01923077 0.01923077 0.01282051 0.01282051 0.01282051
  0.01282051 0.01282051 0.01282051 0.01282051 0.01282051 0.00641026
  0.00641026 0.00641026 0.00641026 0.00641026 0.00641026 0.00641026
  0.00641026 0.00641026 0.00641026 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.    

In [756]:
lr1.predict(t_array)

array(['spam'], dtype=object)

In [757]:
fit=ct1.fit_transform(t_array)

In [758]:
lr1.predict_proba(fit)

array([[0.42021105, 0.57978895]])

In [ ]:
#now model is predicting corrctly!!!!